$(info TEST_LOOPBACK_AUDIO_MK_INC=$(TEST_LOOPBACK_AUDIO_MK_INC))

ifneq ($(TEST_LOOPBACK_AUDIO_MK_INC),Y)
    TEST_LOOPBACK_AUDIO_MK_INC=Y

    TEST_LOOPBACK_AUDIO_DIR = $(TEST_SET_SW_DIR)/test_loopback_audio
    # $(error TEST_LOOPBACK_AUDIO_DIR= $(TEST_LOOPBACK_AUDIO_DIR))

    MCAL_OPT += -DHAS_TEST_SUIT_LOOPBACK_AUDIO
    MCAL_OPT += -DHAS_TEST_LOOPBACK_AUDIO
    INCDIR  += -I$(TEST_LOOPBACK_AUDIO_DIR)

    SOURCES_C += $(TEST_LOOPBACK_AUDIO_DIR)/test_loopback_audio.c
endif
