#ifndef MEDIAN_FILTER_FAST_DEP_H
#define MEDIAN_FILTER_FAST_DEP_H


#ifndef HAS_MEDIAN_FILTER_FAST
#error "+HAS_MEDIAN_FILTER_FAST"
#endif /*HAS_MEDIAN_FILTER_FAST*/

#endif /* MEDIAN_FILTER_FAST_DEP_H */
