$(info MEDIAN_FILTER_FAST_PRECONFIG_MK_INC=$(MEDIAN_FILTER_FAST_PRECONFIG_MK_INC) )

ifneq ($(MEDIAN_FILTER_FAST_PRECONFIG_MK_INC),Y)
    MEDIAN_FILTER_FAST_PRECONFIG_MK_INC=Y

    MEDIAN_FILTER_FAST=Y
    DSP=Y
    MATH=Y
    COMPUTING=Y
endif






