$(info UART_COMMON_PRECONFIG_MCAL_MK_INC=$(UART_COMMON_PRECONFIG_MCAL_MK_INC) )

ifneq ($(UART_COMMON_PRECONFIG_MCAL_MK_INC),Y)
    UART_COMMON_PRECONFIG_MCAL_MK_INC=Y

    FIFO_CHAR=Y
    FIFO_INDEX=Y
    FIFO=Y
    UART=Y
    PINS=Y
    ADT=Y
    CONNECTIVITY=Y
    INTERFACES=Y
endif



