$(info READER_PRECONFIG_MK_LOG=$(READER_PRECONFIG_MK_LOG))

ifneq ($(READER_PRECONFIG_MK_LOG),Y)
    READER_PRECONFIG_MK_LOG=Y

    READER_DRV_DIR = $(PROTOCOLS_DIR)/string_reader

    READER=Y
    STRING=Y
    #READER_CMD_HISTORY=Y
    #CSV=Y
endif