$(info TEST_SOUND_RECORDER_MK_INC=$(TEST_SOUND_RECORDER_MK_INC))

ifneq ($(TEST_SOUND_RECORDER_MK_INC),Y)
    TEST_SOUND_RECORDER_MK_INC=Y

    TEST_SOUND_RECORDER_DIR = $(TEST_SET_SW_DIR)/test_sound_recorder
    #@ $(error TEST_SOUND_RECORDER_DIR= $(TEST_SOUND_RECORDER_DIR))

    MCAL_OPT += -DHAS_TEST_SUIT_SOUND_RECORDER
    MCAL_OPT += -DHAS_TEST_SOUND_RECORDER
    INCDIR  += -I$(TEST_SOUND_RECORDER_DIR)

    SOURCES_C += $(TEST_SOUND_RECORDER_DIR)/test_sound_recorder.c
endif
