$(info MT_32K_LTE_V2_PRECONFIG_MK_INC=$(MT_32K_LTE_V2_PRECONFIG_MK_INC))
ifneq ($(MT_32K_LTE_V2_PRECONFIG_MK_INC),Y)
    MT_32K_LTE_V2_PRECONFIG_MK_INC=Y
    BOARD_CFG_DIR = $(BOARD_DIR)/mt_32k_lte_v2
    #ASICS=Y
    MT_32K_LTE_V2=Y
    ASICS=Y
    STM32=Y
    STM32F407VE=Y
    MICROCONTROLLER=Y
endif
