ifneq ($(DECADRIVER_API_PRECONFIG_MK_INC),Y)
    DECADRIVER_API_PRECONFIG_MK_INC=Y

    DECADRIVER_API_DIR = $(ASICS_DIR)/decadriver
    DECADRIVER=Y
    DW1000=Y
    SPI=Y
    GPIO=Y
    DWM1000=Y
    DECADRIVER_PROC=Y
    UWB=Y
    INTERFACES=Y
    CONNECTIVITY=Y
endif
