message(STATUS "UNIT_TEST_MK_INC=${UNIT_TEST_MK_INC}")
if( NOT (UNIT_TEST_MK_INC STREQUAL Y))
    set(UNIT_TEST_MK_INC Y)
    set(UNIT_TEST Y)
    message(STATUS "Link Unit Test API")
    set(UNIT_TESTS_DIR ${WORKSPACE_LOC}/unit_tests)
 
    message(STATUS "UNIT_TESTS_DIR=${UNIT_TESTS_DIR}")

    target_include_directories(app PUBLIC ${UNIT_TESTS_DIR})
    target_compile_definitions(app PUBLIC HAS_UNIT_TEST)
    target_compile_definitions(app PUBLIC HAS_TEST)
    if( NOT (UNIT_TESTS STREQUAL Y))
        message( FATAL_ERROR "Add UNIT_TESTS")
    endif()

    target_sources(app PRIVATE ${UNIT_TESTS_DIR}/print_buffer.c)
    target_sources(app PRIVATE ${UNIT_TESTS_DIR}/test_config.c)
    target_sources(app PRIVATE ${UNIT_TESTS_DIR}/unit_test.c)
    target_sources(app PRIVATE ${UNIT_TESTS_DIR}/unit_test_run.c)

    if(CLI STREQUAL Y)
        if(UNIT_TEST_COMMANDS STREQUAL Y)
            target_compile_definitions(app PUBLIC HAS_UNIT_TEST_COMMANDS)
            target_sources(app PRIVATE ${UNIT_TESTS_DIR}/unit_test_commands.c)
        endif()
    endif()

    if(TEST_SW STREQUAL Y)
        target_compile_definitions(app PUBLIC HAS_SW_TESTS)
        include(${UNIT_TESTS_DIR}/test_set_sw/test_set_sw.cmake)
    endif()

    if(TEST_HW STREQUAL Y)
        #@echo $(error TEST_HW=$(TEST_HW))
        target_compile_definitions(app PUBLIC HAS_HW_TESTS)
        include(${UNIT_TESTS_DIR}/test_set_hw/test_set_hw.cmake)
    endif()
endif()
