ifneq ($(UNIT_TEST_PRECONFIG_INC),Y)
    UNIT_TEST_PRECONFIG_INC=Y

    CRC16=Y
    UNIT_TEST=Y
    FILE_API=Y
    INDULGENCE_LEVEL_2=Y
    UNIT_TEST_DIAG=Y

    #UNIT_TESTS_DIR=$(WORKSPACE_LOC)/unit_tests
endif