#ifndef __X86_INT_H
#define __X86_INT_H

#ifdef __cplusplus
extern "C" {
#endif

#include "x86x.h"


void BusFault_Handler(void);
void DebugMon_Handler(void);
void HardFault_Handler(void);
void MemManage_Handler(void);
void NMI_Handler(void);
void PendSV_Handler(void);
void SVC_Handler(void);
void SysTick_Handler(void);
void UsageFault_Handler(void);
void FPU_IRQHandler(void);                                /* FPU Handler*/
void WKU_IRQHandler(void);                                /* WKU Handler*/



void  Core0_MB_IRQHandler(void);
void  Core1_MB_IRQHandler(void);
void  Core2_MB_IRQHandler(void);
void  DMA0_IRQHandler(void);
void  DMA1_IRQHandler(void);
void  DMA2_IRQHandler(void);
void  DMA3_IRQHandler(void);
void  DMA4_IRQHandler(void);
void  DMA5_IRQHandler(void);
void  DMA6_IRQHandler(void);
void  DMA7_IRQHandler(void);
void  DMA8_IRQHandler(void);
void  DMA9_IRQHandler(void);
void  DMA10_IRQHandler(void);
void  DMA11_IRQHandler(void);
void  DMA12_IRQHandler(void);
void  DMA13_IRQHandler(void);
void  DMA14_IRQHandler(void);
void  DMA15_IRQHandler(void);
void  DMA16_IRQHandler(void);
void  DMA17_IRQHandler(void);
void  DMA18_IRQHandler(void);
void  DMA19_IRQHandler(void);
void  DMA20_IRQHandler(void);
void  DMA21_IRQHandler(void);
void  DMA22_IRQHandler(void);
void  DMA23_IRQHandler(void);
void  DMA24_IRQHandler(void);
void  DMA25_IRQHandler(void);
void  DMA26_IRQHandler(void);
void  DMA27_IRQHandler(void);
void  DMA28_IRQHandler(void);
void  DMA29_IRQHandler(void);
void  DMA30_IRQHandler(void);
void  DMA31_IRQHandler(void);
void  DMA_Error_IRQHandler(void);
void  CPM_IRQHandler(void);
void  FC_IRQHandler(void);
void  LVD_LVW_IRQHandler(void);
void  TMU_IRQHandler(void);
void  WDOG0_IRQHandler(void);
void  WDOG1_IRQHandler(void);
void  WDOG2_IRQHandler(void);
void  FCSMU0_IRQHandler(void);
void  STCU0_IRQHandler(void);
void  ERM_fault_IRQHandler(void);
void  MAM0_IRQHandler(void);
void  MAM1_IRQHandler(void);
void  MAM2_IRQHandler(void);
void  RESERVED_62_IRQHandler(void);
void  RGM_Pre_IRQHandler(void);
void  RGM_Other_IRQHandler(void);
void  INTM0_IRQHandler(void);
void  ISM0_IRQHandler(void);
void  SCG_IRQHandler(void);
void  CMU0_IRQHandler(void);
void  CMU1_IRQHandler(void);
void  CMU2_IRQHandler(void);
void  CMU3_IRQHandler(void);
void  TSTMP0_IRQHandler(void);
void  TSTMP1_IRQHandler(void);
void  TSTMP2_IRQHandler(void);
void  TSTMP3_IRQHandler(void);
void  CORDIC_IRQHandler(void);
void  HSM0_IRQHandler(void);
void  FCPIT0_IRQHandler(void);
void  FCPIT1_IRQHandler(void);
void  RTC_IRQHandler(void);
void  ENET_Tx0_IRQHandler(void);
void  ENET_Tx1_IRQHandler(void);
void  ENET_Rx0_IRQHandler(void);
void  ENET_Rx1_IRQHandler(void);
void  ENET_System_IRQHandler(void);
void  AONTIMER_IRQHandler(void);
void  SWI_IRQHandler(void);
void  OSPI_IRQHandler(void);
void  FREQM_IRQHandler(void);
void  PORTA_IRQHandler(void);
void  PORTB_IRQHandler(void);
void  PORTC_IRQHandler(void);
void  PORTD_IRQHandler(void);
void  PORTE_IRQHandler(void);
void  PORTF_IRQHandler(void);
void  PORTG_IRQHandler(void);
void  PORTH_IRQHandler(void);
void  PORTI_IRQHandler(void);
void  CAN0_IRQHandler(void);
void  CAN1_IRQHandler(void);
void  CAN2_IRQHandler(void);
void  CAN3_IRQHandler(void);
void  CAN4_IRQHandler(void);
void  CAN5_IRQHandler(void);
void  CAN6_IRQHandler(void);
void  CAN7_IRQHandler(void);
void  FCIIC0_IRQHandler(void);
void  FCIIC1_IRQHandler(void);
void  FCSPI0_IRQHandler(void);
void  FCSPI1_IRQHandler(void);
void  FCSPI2_IRQHandler(void);
void  FCSPI3_IRQHandler(void);
void  FCSPI4_IRQHandler(void);
void  FCSPI5_IRQHandler(void);
void  FCUART0_RxTx_IRQHandler(void);
void  FCUART1_RxTx_IRQHandler(void);
void  FCUART2_RxTx_IRQHandler(void);
void  FCUART3_RxTx_IRQHandler(void);
void  FCUART4_RxTx_IRQHandler(void);
void  FCUART5_RxTx_IRQHandler(void);
void  FCUART6_RxTx_IRQHandler(void);
void  FCUART7_RxTx_IRQHandler(void);
void  FCUART8_RxTx_IRQHandler(void);
void  FCUART9_RxTx_IRQHandler(void);
void  FCUART10_RxTx_IRQHandler(void);
void  FCUART11_RxTx_IRQHandler(void);
void  FCUART12_RxTx_IRQHandler(void);
void  FCUART13_RxTx_IRQHandler(void);
void  FCUART14_RxTx_IRQHandler(void);
void  FCUART15_RxTx_IRQHandler(void);
void  FTU0_IRQHandler(void);
void  FTU1_IRQHandler(void);
void  FTU2_IRQHandler(void);
void  FTU3_IRQHandler(void);
void  FTU4_IRQHandler(void);
void  FTU5_IRQHandler(void);
void  FTU6_IRQHandler(void);
void  FTU7_IRQHandler(void);
void  FTU8_IRQHandler(void);
void  FTU9_IRQHandler(void);
void  FTU10_IRQHandler(void);
void  FTU11_IRQHandler(void);
void  CMP0_IRQHandler(void);
void  CMP1_IRQHandler(void);
void  CMP2_IRQHandler(void);
void  ADC0_IRQHandler(void);
void  ADC1_IRQHandler(void);
void  ADC2_IRQHandler(void);
void  ADC3_IRQHandler(void);
void  PTIMER0_IRQHandler(void);
void  PTIMER1_IRQHandler(void);
void  PTIMER2_IRQHandler(void);
void  PTIMER3_IRQHandler(void);
void  SDDF0_IRQHandler(void);
void  MSC0_IRQHandler(void);
void  MSC1_IRQHandler(void);
void  CAN8_IRQHandler(void);
void  CAN9_IRQHandler(void);
void  SENT0_IRQHandler(void);
void  SENT1_IRQHandler(void);
void  FCSPI6_IRQHandler(void);
void  FCSPI7_IRQHandler(void);
void  FCUART16_RxTx_IRQHandler(void);
void  FCUART17_RxTx_IRQHandler(void);
void  CTI0_IRQHandler(void);
void  CTI1_IRQHandler(void);
void  CTI2_IRQHandler(void);

#ifdef __cplusplus
}
#endif

#endif
