#include "pin_config.h"

#include <stdint.h>

#include "data_utils.h"

const PinData_t PinConfig[] = {
   {.mcu_pin=1, .pad.port=0, .pad.pin=0,  .valid=true,},
   {.mcu_pin=1, .pad.port=0, .pad.pin=1,  .valid=true,},
   {.mcu_pin=1, .pad.port=0, .pad.pin=2,  .valid=true, },
   {.mcu_pin=1, .pad.port=0, .pad.pin=3,  .valid=true, },
   {.mcu_pin=2, .pad.port=0, .pad.pin=4,  .valid=true, },
   {.mcu_pin=2, .pad.port=0, .pad.pin=5,  .valid=true, },
   {.mcu_pin=2, .pad.port=0, .pad.pin=6,  .valid=true, },
   {.mcu_pin=2, .pad.port=0, .pad.pin=7,  .valid=true, },
   {.mcu_pin=2, .pad.port=0, .pad.pin=8,  .valid=true, },
   {.mcu_pin=1, .pad.port=0, .pad.pin=9,  .valid=true, },
   {.mcu_pin=2, .pad.port=0, .pad.pin=10, .valid=true,  },
   {.mcu_pin=4, .pad.port=0, .pad.pin=11, .valid=true,  },
   {.mcu_pin=6, .pad.port=0, .pad.pin=12, .valid=true,  },
   {.mcu_pin=5, .pad.port=0, .pad.pin=13, .valid=true,  },
   {.mcu_pin=8, .pad.port=0, .pad.pin=14, .valid=true,  },
   {.mcu_pin=10,.pad.port=0, .pad.pin=15, .valid=true,  },
   {.mcu_pin=9, .pad.port=0, .pad.pin=16, .valid=true,  },
   {.mcu_pin=12,.pad.port=0, .pad.pin=17, .valid=true,  },
   {.mcu_pin=14,.pad.port=0, .pad.pin=18, .valid=true,  },
   {.mcu_pin=19,.pad.port=0, .pad.pin=19, .valid=true,  },
   {.mcu_pin=13,.pad.port=0, .pad.pin=20, .valid=true,  },
   {.mcu_pin=15,.pad.port=0, .pad.pin=21, .valid=true,  },
   {.mcu_pin=18,.pad.port=0, .pad.pin=22, .valid=true,  },
   {.mcu_pin=20,.pad.port=0, .pad.pin=23, .valid=true,  },
   {.mcu_pin=27,.pad.port=0, .pad.pin=24, .valid=true,  },
   {.mcu_pin=28,.pad.port=0, .pad.pin=25, .valid=true,  },
   {.mcu_pin=29,.pad.port=0, .pad.pin=26, .valid=true,  },
   {.mcu_pin=30,.pad.port=0, .pad.pin=27, .valid=true,  },
   {.mcu_pin=31,.pad.port=0, .pad.pin=28, .valid=true,  },
   {.mcu_pin=31,.pad.port=0,  .pad.pin=29,.valid=true,  },
   {.mcu_pin=24,.pad.port=0,  .pad.pin=30,.valid=true,  },
   {.mcu_pin=22,.pad.port=0, .pad.pin=31, .valid=true, },
   {.mcu_pin=2,.pad.port=1, .pad.pin=0,  .valid=true,},
   {.mcu_pin=2,.pad.port=1, .pad.pin=1,  .valid=true,},
   {.mcu_pin=1,.pad.port=1, .pad.pin=2,  .valid=true,},
   {.mcu_pin=2,.pad.port=1, .pad.pin=3,  .valid=true,},
   {.mcu_pin=19,.pad.port=1, .pad.pin=4,  .valid=true,},
   {.mcu_pin=22,.pad.port=1, .pad.pin=5,  .valid=true,},
   {.mcu_pin=21,.pad.port=1, .pad.pin=6,  .valid=true,},
   {.mcu_pin=24,.pad.port=1, .pad.pin=7,  .valid=true,},
   {.mcu_pin=23,.pad.port=1, .pad.pin=8,  .valid=true,},
   {.mcu_pin=26,.pad.port=1, .pad.pin=9,  .valid=true,},
   {.mcu_pin=31,.pad.port=1, .pad.pin=10, .valid=true, },
   {.mcu_pin=20,.pad.port=1, .pad.pin=11, .valid=true, },
   {.mcu_pin=18,.pad.port=1, .pad.pin=12, .valid=true, },
   {.mcu_pin=17,.pad.port=1, .pad.pin=13, .valid=true, },
   {.mcu_pin=16,.pad.port=1, .pad.pin=14, .valid=true, },
   {.mcu_pin=14,.pad.port=1, .pad.pin=15, .valid=true, },
   {.mcu_pin=46,.pad.port=1, .pad.pin=16, .valid=true, },
   {.mcu_pin=47,.pad.port=1, .pad.pin=17, .valid=true, },
   {.mcu_pin=48,.pad.port=1, .pad.pin=18, .valid=true, },
   {.mcu_pin=49,.pad.port=1, .pad.pin=19, .valid=true, },
   {.mcu_pin=50,.pad.port=1, .pad.pin=20, .valid=true, },
   {.mcu_pin=51,.pad.port=1, .pad.pin=21, .valid=true, },
   {.mcu_pin=52,.pad.port=1, .pad.pin=22, .valid=true, },
   {.mcu_pin=53,.pad.port=1, .pad.pin=23, .valid=true, },
   {.mcu_pin=54,.pad.port=1, .pad.pin=24, .valid=true, },
   {.mcu_pin=55,.pad.port=1, .pad.pin=25, .valid=true, },
   {.mcu_pin=56,.pad.port=1, .pad.pin=26, .valid=true, },
   {.mcu_pin=57,.pad.port=1, .pad.pin=27, .valid=true, },
   {.mcu_pin=58,.pad.port=1, .pad.pin=28, .valid=true, },
   {.mcu_pin=59,.pad.port=1, .pad.pin=29, .valid=true, },
   {.mcu_pin=60,.pad.port=1, .pad.pin=30, .valid=true, },
   {.mcu_pin=61,.pad.port=1, .pad.pin=31, .valid=true, },
   {.mcu_pin=62,  },
   {.mcu_pin=63,  },
   {.mcu_pin=64,  },
   {.mcu_pin=65,  },
   {.mcu_pin=66,  },
   {.mcu_pin=67,  },
   {.mcu_pin=68,  },
   {.mcu_pin=69,  },
   {.mcu_pin=70,  },
   {.mcu_pin=71, },
   {.mcu_pin=72, },
   {.mcu_pin=73, },
   {.mcu_pin=74, },
   {.mcu_pin=75, },
   {.mcu_pin=76, },
   {.mcu_pin=77, },
   {.mcu_pin=78, },
   {.mcu_pin=79, },
   {.mcu_pin=80, },
   {.mcu_pin=81, },
   {.mcu_pin=82, },
   {.mcu_pin=83, },
   {.mcu_pin=84, },
   {.mcu_pin=85,},
   {.mcu_pin=86,},
   {.mcu_pin=87,},
   {.mcu_pin=88,},
   {.mcu_pin=89,},
   {.mcu_pin=90,},
   {.mcu_pin=91,},
   {.mcu_pin=92,},
   {.mcu_pin=93,},
   {.mcu_pin=94,},

};



uint16_t pin_get_cnt(void) {
    uint16_t cnt = 0;
    cnt = ARRAY_SIZE(PinConfig);
    return cnt;
}

