$(info START_MIK32_V1_PRECONFIG_MK_INC=$(START_MIK32_V1_PRECONFIG_MK_INC))
ifneq ($(START_MIK32_V1_PRECONFIG_MK_INC),Y)
    START_MIK32_V1_PRECONFIG_MK_INC=Y

    BOARD_CFG_DIR = $(BOARD_DIR)/start_mik32_v1

    #ASICS=Y
    START_MIK32_V1=Y
    #ASICS=Y
    MIK32=Y
    K1948BK018=Y
    MICROCONTROLLER=Y
endif
