$(info AT24CXX_PRECONFIG_MK_INC=$(AT24CXX_PRECONFIG_MK_INC) )

ifneq ($(AT24CXX_PRECONFIG_MK_INC),Y)
    AT24CXX_PRECONFIG_MK_INC=Y

    AT24CXX_DIR = $(WORKSPACE_LOC)asics/at24cxx

    AT24CXX=Y
    TIME=Y
    I2C=Y
    GPIO=Y
endif
