$(info CAN_STM32_DRV_PRECONFIG_INC=  $(CAN_STM32_DRV_PRECONFIG_INC) )
ifneq ($(CAN_STM32_DRV_PRECONFIG_INC),Y)
    CAN_STM32_DRV_PRECONFIG_INC=Y
    #$(error  CAN_STM32_DRV_PRECONFIG )
    CAN=Y
    GPIO=Y
    TIME=Y
    MCAL=Y
    CONNECTIVITY=Y
    #CAN_INTERRUPT=Y
    INTERFACES=Y
    INTERRUPT=Y
endif