$(info JL_32F4XX_PRECONFIG_MK_INC=$(JL_32F4XX_PRECONFIG_MK_INC))
ifneq ($(JL_32F4XX_PRECONFIG_MK_INC),Y)
    JL_32F4XX_PRECONFIG_MK_INC=Y

    BOARD_CFG_DIR = $(BOARD_DIR)/jl_32f4xx

    ASICS=Y
    JL_32F4XX=Y
    STM32=Y
    STM32F407VG=Y
    MICROCONTROLLER=Y

endif
