$(info LTR390_PRECONFIG_INC=$(LTR390_PRECONFIG_INC) )

ifneq ($(LTR390_PRECONFIG_INC),Y)
    LTR390_PRECONFIG_INC=Y

    ASICS=Y
    LTR390=Y
    MICROCONTROLLER=Y
    SENSITIVITY=Y
    I2C=Y
    GPIO=Y
    MCAL=Y
endif
