$(info RTC_GENERAL_PRECONFIG_MCAL_MK_INC=$(RTC_GENERAL_PRECONFIG_MCAL_MK_INC) )

ifneq ($(RTC_GENERAL_PRECONFIG_MCAL_MK_INC),Y)
    RTC_GENERAL_PRECONFIG_MCAL_MK_INC=Y
    #@echo $(error RTC_GENERAL_PRECONFIG_MCAL_MK_INC=$(RTC_GENERAL_PRECONFIG_MCAL_MK_INC))
    RTC=Y
    TIME=Y
    DATE=Y
    SENSITIVITY=Y
endif






