$(info OLIMEX_H407_PRECONFIG_MK_INC=$(OLIMEX_H407_PRECONFIG_MK_INC))
ifneq ($(OLIMEX_H407_PRECONFIG_MK_INC),Y)
    OLIMEX_H407_PRECONFIG_MK_INC=Y


    BOARD_CFG_DIR = $(BOARD_DIR)/olimex_stm32_h407

    #ASICS=Y
    OLIMEX_H407=Y
    ASICS=Y
    STM32=Y
    STM32F407ZG=Y
    MICROCONTROLLER=Y

endif
