#ifndef AUTO_VERSION_H
#define AUTO_VERSION_H

<<<<<<< HEAD
#define SUCCESSFUL_BUILD_COUNTER 24
=======
#define SUCCESSFUL_BUILD_COUNTER 9
>>>>>>> 47e20a8a139b71f477c940658dc81793c68a7e27

#define GIT_BRANCH  "GIT_BRANCH_AUTO_REPLACE"
#define GIT_LAST_COMMIT_HASH  "GIT_LAST_COMMIT_HASH_AUTO_REPLACE"

#endif /*AUTO_VERSION_H*/
