$(info CAN_X8632_DRV_PRECONFIG_INC=  $(CAN_X8632_DRV_PRECONFIG_INC) )
ifneq ($(CAN_X8632_DRV_PRECONFIG_INC),Y)
    CAN_X8632_DRV_PRECONFIG_INC=Y
    # $(error  CAN_X8632_DRV_PRECONFIG )
    CAN=Y
    MCAL=Y
    CONNECTIVITY=Y
    INTERFACES=Y
endif