$(info Build SALSA20_PRECONFIG_MK=$(SALSA20_PRECONFIG_MK))

ifneq ($(SALSA20_PRECONFIG_MK),Y)
    SALSA20_PRECONFIG_MK=Y

    SALSA20_DIR = $(SECURITY_DIR)/salsa20
    
    SALSA20=Y
    SECURITY=Y
endif
