
#ifndef STM32F411CE_CONST_H
#define STM32F411CE_CONST_H

#include <stm32f411xe.h>

#include "macro_utils.h"

#define I2C_COUNT 3
#define ADC_COUNT 1
#define TIMER_COUNT 8
#define SPI_COUNT 5
#define I2S_COUNT 5
#define CAN_COUNT 0
#define CRY_COUNT 0
#define SDIO_COUNT 1
#define CPU_MAX_HZ 100000000
#define LSI_FREQ 32000
#define MCU_NAME "stm32f411ce"
#define MCU_PACKAGE  "LQFP48"
#define RAM_START 0x20000000
#define ROM_SIZE (512 * K_BYTES)
#define ROM_START 0x08000000
#define SYS_FREQ 100000000
#define UART_COUNT 3
#define USB_COUNT 1
#define RAM_SIZE (128 * K_BYTES)
#define GPIO_PIN_MAX 15
#define CRC_COUNT 1
#define DAC_COUNT 0
#define DMA_COUNT 2
#define TRNG_COUNT 0
#define RTC_COUNT 1
#define ADC_CHANNELS_COUNT 16
#define AHB1_CLOCK_HZ SYS_FREQ
#define DAC_CHANNELS_COUNT 0
#define RAM_END (RAM_START + RAM_SIZE)
#define ROM_END (ROM_START + ROM_SIZE)
#define NOR_FLASH_START ROM_START
#define GPIO_COUNT 36
#define DMA_STREAM_COUNT 8
#define MAX_IRQ_NUM SPI5_IRQn
#define APB1_CLOCK_HZ (AHB1_CLOCK_HZ/2)
#define APB2_CLOCK_HZ (AHB1_CLOCK_HZ)
#define TIMER_MAX_COUNT (11)

#define NOR_FLASH_BASE ROM_START

#endif /* STM32F411CE_CONST_H */
