$(info CORRELATOR_S16_PRECONFIG_INC=$(CORRELATOR_S16_PRECONFIG_INC) )

ifneq ($(CORRELATOR_S16_PRECONFIG_INC),Y)
    CORRELATOR_S16_PRECONFIG_INC=Y

    CORRELATOR_S16=Y
    CIRCULAR_BUFFER=Y
    DSP=Y
endif
