$(info TEST_SCHMITT_TRIGGER_MK_INC=$(TEST_SCHMITT_TRIGGER_MK_INC))

ifneq ($(TEST_SCHMITT_TRIGGER_MK_INC),Y)
    TEST_SCHMITT_TRIGGER_MK_INC=Y

    ifneq ($(SCHMITT_TRIGGER),Y)
        @echo $(error +SCHMITT_TRIGGER)
    endif

    TEST_SCHMITT_TRIGGER_DIR = $(TEST_SET_SW_DIR)/test_schmitt_trigger
    #@echo $(error TEST_SCHMITT_TRIGGER_DIR= $(TEST_SCHMITT_TRIGGER_DIR))

    OPT += -DHAS_TEST_SUIT_SCHMITT_TRIGGER
    OPT += -DHAS_TEST_SCHMITT_TRIGGER

    INCDIR  += -I$(TEST_SCHMITT_TRIGGER_DIR)

    SOURCES_C += $(TEST_SCHMITT_TRIGGER_DIR)/test_schmitt_trigger.c
endif
