message(STATUS "WM8731_CMK_INC=${WM8731_CMK_INC}")
if( NOT (WM8731_CMK_INC STREQUAL Y))
    set(WM8731_CMK_INC Y)
    message(STATUS "+ Wm8731 driver")

    set(WM8731_DIR ${ASICS_DIR}/wm8731)
    message(STATUS "WM8731_DIR=${WM8731_DIR}")
    
    message(STATUS "WM8731_VERIFY=[${WM8731_VERIFY}]")
    message(STATUS "WM8731_NORMAL_MODE=[${WM8731_NORMAL_MODE}]")
    message(STATUS "WM8731_USB_MODE=[${WM8731_USB_MODE}]")
    message(STATUS "WM8731_I2S_SLAVE=[${WM8731_I2S_SLAVE}]")
    message(STATUS "WM8731_I2S_MASTER=[${WM8731_I2S_MASTER}]")
    message(STATUS "WM8731_DIAG=[${WM8731_DIAG}]")
    message(STATUS "WM8731_COMMANDS=[${WM8731_COMMANDS}]")

    add_compile_definitions(HAS_WM8731)
    target_compile_definitions(app PUBLIC HAS_WM8731)

    if(WM8731_NORMAL_MODE STREQUAL Y)
        message(STATUS "+WM8731_NORMAL_MODE")
        target_compile_definitions(app PUBLIC HAS_WM8731_NORMAL_MODE)
    endif()

    if(WM8731_USB_MODE STREQUAL Y)
        message(STATUS "+WM8731_USB_MODE")
        target_compile_definitions(app PUBLIC HAS_WM8731_USB_MODE)
    endif()

    if(WM8731_NORMAL_MODE STREQUAL Y)
        if(WM8731_USB_MODE STREQUAL Y)
            message( SEND_ERROR "Double clock mode contradiction")
        endif()
    endif()

    if (WM8731_VERIFY STREQUAL Y)
        message(STATUS "+WM8731_VERIFY")
        target_compile_definitions(app PUBLIC HAS_WM8731_VERIFY)
    endif()

    target_include_directories(app PUBLIC ${WM8731_DIR})
    target_sources(app PRIVATE ${WM8731_DIR}/wm8731_drv.c)

    if(WM8731_I2S_SLAVE STREQUAL Y)
        message(STATUS "+HAS_WM8731_I2S_SLAVE")
        target_compile_definitions(app PUBLIC HAS_WM8731_I2S_SLAVE)
    endif()

    if(WM8731_I2S_MASTER STREQUAL Y)
        message(STATUS "+HAS_WM8731_I2S_MASTER")
        target_compile_definitions(app PUBLIC HAS_WM8731_I2S_MASTER)
    endif()

    if(DIAG STREQUAL Y)
        if(WM8731_DIAG STREQUAL Y)
            message(STATUS "+WM8731_DIAG")
            target_compile_definitions(app PUBLIC HAS_WM8731_DIAG)
            target_sources(app PRIVATE ${WM8731_DIR}/wm8731_diag.c)
        endif()
    endif()

    if(CLI STREQUAL Y)
        if(WM8731_COMMANDS STREQUAL Y)
            message(STATUS "+WM8731_COMMANDS")
            target_compile_definitions(app PUBLIC HAS_WM8731_COMMANDS)
            target_sources(app PRIVATE ${WM8731_DIR}/wm8731_commands.c)
        endif()
    endif()
endif()
