#ifndef WAV_CONST_H
#define WAV_CONST_H

#include "wav_dep.h"

#define WAV_SECTION_FMT_SIZE 16

#define WAV_RIFF 0x52494646

#define WAV_WAVE 0x57415645


typedef enum {
    WAV_SECTION_ID_FMT  = 0x666D7420,
    WAV_SECTION_ID_DATA = 0x64617461,
    WAV_SECTION_ID_FACT=  0x66616374,
    //WAV_SECTION_ID_WAVL = 0x736C6E74,
    //WAV_SECTION_ID_SILENT =0x736C6E74,
    WAV_SECTION_ID_LABL =0x6C61626C,
    WAV_SECTION_ID_LIST = 0x6C696E74,
    WAV_SECTION_ID_CUE =0x63756520,
    WAV_SECTION_ID_NOTE =0x6E6F7465,
    WAV_SECTION_ID_LTXT =0x6C747874,
}WavSectopn_t;

/*Common Wave Compression Codes*/
typedef enum {
    WAVE_COMPRESSION_CODE_UNKNOWN = 0x0000, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_PCM = 0x0001, /* PCM/uncompressed */
    WAVE_COMPRESSION_CODE_ADPCM = 0x0002, /* Microsoft ADPCM */
    WAVE_COMPRESSION_CODE_IEEE_FLOAT = 0x0003, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_VSELP = 0x0004, /* Compaq Computer Corp. */
    WAVE_COMPRESSION_CODE_IBM_CVSD = 0x0005, /* IBM Corporation */
    WAVE_COMPRESSION_CODE_ALAW = 0x0006, /* ITU G.711 a-law */
    WAVE_COMPRESSION_CODE_MULAW = 0x0007, /* ITU G.711 µ-law */
    WAVE_COMPRESSION_CODE_DTS = 0x0008, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_DRM = 0x0009, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_OKI_ADPCM = 0x0010, /* OKI */
    WAVE_COMPRESSION_CODE_DVI_ADPCM = 0x0011, /*IMA ADPCM */
    WAVE_COMPRESSION_CODE_IMA_ADPCM = (WAVE_COMPRESSION_CODE_DVI_ADPCM), /* Intel Corporation */
    WAVE_COMPRESSION_CODE_MEDIASPACE_ADPCM = 0x0012, /* Videologic */
    WAVE_COMPRESSION_CODE_SIERRA_ADPCM = 0x0013, /* Sierra Semiconductor Corp */
    WAVE_COMPRESSION_CODE_G723_ADPCM = 0x0014, /* Antex Electronics Corporation */
    WAVE_COMPRESSION_CODE_DIGISTD = 0x0015, /* DSP Solutions, Inc. */
    WAVE_COMPRESSION_CODE_DIGIFIX = 0x0016, /* ITU G.723 ADPCM (Yamaha) DSP Solutions, Inc. */
    WAVE_COMPRESSION_CODE_DIALOGIC_OKI_ADPCM = 0x0017, /* Dialogic Corporation */
    WAVE_COMPRESSION_CODE_MEDIAVISION_ADPCM = 0x0018, /* Media Vision, Inc. */
    WAVE_COMPRESSION_CODE_CU_CODEC = 0x0019, /* Hewlett-Packard Company */
    WAVE_COMPRESSION_CODE_YAMAHA_ADPCM = 0x0020, /* Yamaha Corporation of America */
    WAVE_COMPRESSION_CODE_SONARC = 0x0021, /* Speech Compression */
    WAVE_COMPRESSION_CODE_DSPGROUP_TRUESPEECH = 0x0022, /* DSP Group, Inc */
    WAVE_COMPRESSION_CODE_ECHOSC1 = 0x0023, /* Echo Speech Corporation */
    WAVE_COMPRESSION_CODE_AUDIOFILE_AF36 = 0x0024, /* Virtual Music, Inc. */
    WAVE_COMPRESSION_CODE_APTX = 0x0025, /* Audio Processing Technology */
    WAVE_COMPRESSION_CODE_AUDIOFILE_AF10 = 0x0026, /* Virtual Music, Inc. */
    WAVE_COMPRESSION_CODE_PROSODY_1612 = 0x0027, /* Aculab plc */
    WAVE_COMPRESSION_CODE_LRC = 0x0028, /* Merging Technologies S.A. */
    WAVE_COMPRESSION_CODE_DOLBY_AC2 = 0x0030, /* Dolby Laboratories */
    WAVE_COMPRESSION_CODE_GSM610 = 0x0031, /* GSM 6.10 Microsoft Corporation */
    WAVE_COMPRESSION_CODE_MSNAUDIO = 0x0032, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_ANTEX_ADPCME = 0x0033, /* Antex Electronics Corporation */
    WAVE_COMPRESSION_CODE_CONTROL_RES_VQLPC = 0x0034, /* Control Resources Limited */
    WAVE_COMPRESSION_CODE_DIGIREAL = 0x0035, /* DSP Solutions, Inc. */
    WAVE_COMPRESSION_CODE_DIGIADPCM = 0x0036, /* DSP Solutions, Inc. */
    WAVE_COMPRESSION_CODE_CONTROL_RES_CR10 = 0x0037, /* Control Resources Limited */
    WAVE_COMPRESSION_CODE_NMS_VBXADPCM = 0x0038, /* Natural MicroSystems */
    WAVE_COMPRESSION_CODE_CS_IMAADPCM = 0x0039, /* Crystal Semiconductor IMA ADPCM */
    WAVE_COMPRESSION_CODE_ECHOSC3 = 0x003A, /* Echo Speech Corporation */
    WAVE_COMPRESSION_CODE_ROCKWELL_ADPCM = 0x003B, /* Rockwell International */
    WAVE_COMPRESSION_CODE_ROCKWELL_DIGITALK = 0x003C, /* Rockwell International */
    WAVE_COMPRESSION_CODE_XEBEC = 0x003D, /* Xebec Multimedia Solutions Limited */
    WAVE_COMPRESSION_CODE_G721_ADPCM = 0x0040, /* ITU G.721 ADPCM Antex Electronics Corporation */
    WAVE_COMPRESSION_CODE_G728_CELP = 0x0041, /* Antex Electronics Corporation */
    WAVE_COMPRESSION_CODE_MSG723 = 0x0042, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_MPEG = 0x0050, /* MPEG Microsoft Corporation */
    WAVE_COMPRESSION_CODE_RT24 = 0x0052, /* InSoft, Inc. */
    WAVE_COMPRESSION_CODE_PAC = 0x0053, /* InSoft, Inc. */
    WAVE_COMPRESSION_CODE_MPEGLAYER3 = 0x0055, /* ISO/MPEG Layer3 Format Tag */
    WAVE_COMPRESSION_CODE_LUCENT_G723 = 0x0059, /* Lucent Technologies */
    WAVE_COMPRESSION_CODE_CIRRUS = 0x0060, /* Cirrus Logic */
    WAVE_COMPRESSION_CODE_ESPCM = 0x0061, /* ESS Technology */
    WAVE_COMPRESSION_CODE_VOXWARE = 0x0062, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_CANOPUS_ATRAC = 0x0063, /* Canopus, co., Ltd. */
    WAVE_COMPRESSION_CODE_G726_ADPCM = 0x0064, /* APICOM */
    WAVE_COMPRESSION_CODE_G722_ADPCM = 0x0065, /* APICOM */
    WAVE_COMPRESSION_CODE_DSAT_DISPLAY = 0x0067, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_VOXWARE_BYTE_ALIGNED = 0x0069, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_AC8 = 0x0070, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_AC10 = 0x0071, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_AC16 = 0x0072, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_AC20 = 0x0073, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_RT24 = 0x0074, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_RT29 = 0x0075, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_RT29HW = 0x0076, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_VR12 = 0x0077, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_VR18 = 0x0078, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_VOXWARE_TQ40 = 0x0079, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_SOFTSOUND = 0x0080, /* Softsound, Ltd. */
    WAVE_COMPRESSION_CODE_VOXWARE_TQ60 = 0x0081, /* Voxware Inc */
    WAVE_COMPRESSION_CODE_MSRT24 = 0x0082, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_G729A = 0x0083, /* AT&amp;T Labs, Inc. */
    WAVE_COMPRESSION_CODE_MVI_MVI2 = 0x0084, /* Motion Pixels */
    WAVE_COMPRESSION_CODE_DF_G726 = 0x0085, /* DataFusion Systems (Pty) (Ltd) */
    WAVE_COMPRESSION_CODE_DF_GSM610 = 0x0086, /* DataFusion Systems (Pty) (Ltd) */
    WAVE_COMPRESSION_CODE_ISIAUDIO = 0x0088, /* Iterated Systems, Inc. */
    WAVE_COMPRESSION_CODE_ONLIVE = 0x0089, /* OnLive! Technologies, Inc. */
    WAVE_COMPRESSION_CODE_SBC24 = 0x0091, /* Siemens Business Communications Sys */
    WAVE_COMPRESSION_CODE_DOLBY_AC3_SPDIF = 0x0092, /* Sonic Foundry */
    WAVE_COMPRESSION_CODE_MEDIASONIC_G723 = 0x0093, /* MediaSonic */
    WAVE_COMPRESSION_CODE_PROSODY_8KBPS = 0x0094, /* Aculab plc */
    WAVE_COMPRESSION_CODE_ZYXEL_ADPCM = 0x0097, /* ZyXEL Communications, Inc. */
    WAVE_COMPRESSION_CODE_PHILIPS_LPCBB = 0x0098, /* Philips Speech Processing */
    WAVE_COMPRESSION_CODE_PACKED = 0x0099, /* Studer Professional Audio AG */
    WAVE_COMPRESSION_CODE_MALDEN_PHONYTALK = 0x00A0, /* Malden Electronics Ltd. */
    WAVE_COMPRESSION_CODE_RHETOREX_ADPCM = 0x0100, /* Rhetorex Inc. */
    WAVE_COMPRESSION_CODE_IRAT = 0x0101, /* BeCubed Software Inc. */
    WAVE_COMPRESSION_CODE_VIVO_G723 = 0x0111, /* Vivo Software */
    WAVE_COMPRESSION_CODE_VIVO_SIREN = 0x0112, /* Vivo Software */
    WAVE_COMPRESSION_CODE_DIGITAL_G723 = 0x0123, /* Digital Equipment Corporation */
    WAVE_COMPRESSION_CODE_SANYO_LD_ADPCM = 0x0125, /* Sanyo Electric Co., Ltd. */
    WAVE_COMPRESSION_CODE_SIPROLAB_ACEPLNET = 0x0130, /* Sipro Lab Telecom Inc. */
    WAVE_COMPRESSION_CODE_SIPROLAB_ACELP4800 = 0x0131, /* Sipro Lab Telecom Inc. */
    WAVE_COMPRESSION_CODE_SIPROLAB_ACELP8V3 = 0x0132, /* Sipro Lab Telecom Inc. */
    WAVE_COMPRESSION_CODE_SIPROLAB_G729 = 0x0133, /* Sipro Lab Telecom Inc. */
    WAVE_COMPRESSION_CODE_SIPROLAB_G729A = 0x0134, /* Sipro Lab Telecom Inc. */
    WAVE_COMPRESSION_CODE_SIPROLAB_KELVIN = 0x0135, /* Sipro Lab Telecom Inc. */
    WAVE_COMPRESSION_CODE_G726ADPCM = 0x0140, /* Dictaphone Corporation */
    WAVE_COMPRESSION_CODE_QUALCOMM_PUREVOICE = 0x0150, /* Qualcomm, Inc. */
    WAVE_COMPRESSION_CODE_QUALCOMM_HALFRATE = 0x0151, /* Qualcomm, Inc. */
    WAVE_COMPRESSION_CODE_TUBGSM = 0x0155, /* Ring Zero Systems, Inc. */
    WAVE_COMPRESSION_CODE_MSAUDIO1 = 0x0160, /* Microsoft Corporation */
    WAVE_COMPRESSION_CODE_UNISYS_NAP_ADPCM = 0x0170, /* Unisys Corp. */
    WAVE_COMPRESSION_CODE_UNISYS_NAP_ULAW = 0x0171, /* Unisys Corp. */
    WAVE_COMPRESSION_CODE_UNISYS_NAP_ALAW = 0x0172, /* Unisys Corp. */
    WAVE_COMPRESSION_CODE_UNISYS_NAP_16K = 0x0173, /* Unisys Corp. */
    WAVE_COMPRESSION_CODE_CREATIVE_ADPCM = 0x0200, /* Creative Labs, Inc */
    WAVE_COMPRESSION_CODE_CREATIVE_FASTSPEECH8 = 0x0202, /* Creative Labs, Inc */
    WAVE_COMPRESSION_CODE_CREATIVE_FASTSPEECH10 = 0x0203, /* Creative Labs, Inc */
    WAVE_COMPRESSION_CODE_UHER_ADPCM = 0x0210, /* UHER informatic GmbH */
    WAVE_COMPRESSION_CODE_QUARTERDECK = 0x0220, /* Quarterdeck Corporation */
    WAVE_COMPRESSION_CODE_ILINK_VC = 0x0230, /* I-link Worldwide */
    WAVE_COMPRESSION_CODE_RAW_SPORT = 0x0240, /* Aureal Semiconductor */
    WAVE_COMPRESSION_CODE_ESST_AC3 = 0x0241, /* ESS Technology, Inc. */
    WAVE_COMPRESSION_CODE_IPI_HSX = 0x0250, /* Interactive Products, Inc. */
    WAVE_COMPRESSION_CODE_IPI_RPELP = 0x0251, /* Interactive Products, Inc. */
    WAVE_COMPRESSION_CODE_CS2 = 0x0260, /* Consistent Software */
    WAVE_COMPRESSION_CODE_SONY_SCX = 0x0270, /* Sony Corp. */
    WAVE_COMPRESSION_CODE_FM_TOWNS_SND = 0x0300, /* Fujitsu Corp. */
    WAVE_COMPRESSION_CODE_BTV_DIGITAL = 0x0400, /* Brooktree Corporation */
    WAVE_COMPRESSION_CODE_QDESIGN_MUSIC = 0x0450, /* QDesign Corporation */
    WAVE_COMPRESSION_CODE_VME_VMPCM = 0x0680, /* AT&amp;T Labs, Inc. */
    WAVE_COMPRESSION_CODE_TPC = 0x0681, /* AT&amp;T Labs, Inc. */
    WAVE_COMPRESSION_CODE_OLIGSM = 0x1000, /* Ing C. Olivetti &amp; C., S.p.A. */
    WAVE_COMPRESSION_CODE_OLIADPCM = 0x1001, /* Ing C. Olivetti &amp; C., S.p.A. */
    WAVE_COMPRESSION_CODE_OLICELP = 0x1002, /* Ing C. Olivetti &amp; C., S.p.A. */
    WAVE_COMPRESSION_CODE_OLISBC = 0x1003, /* Ing C. Olivetti &amp; C., S.p.A. */
    WAVE_COMPRESSION_CODE_OLIOPR = 0x1004, /* Ing C. Olivetti &amp; C., S.p.A. */
    WAVE_COMPRESSION_CODE_LH_CODEC = 0x1100, /* Lernout &amp; Hauspie */
    WAVE_COMPRESSION_CODE_NORRIS = 0x1400, /* Norris Communications, Inc. */
    WAVE_COMPRESSION_CODE_SOUNDSPACE_MUSICOMPRESS = 0x1500, /* AT&amp;T Labs, Inc. */
    WAVE_COMPRESSION_CODE_DVM = 0x2000, /* FAST Multimedia AG */
    WAVE_COMPRESSION_CODE_EXPERIMENTAL = 0xFFFF, /* Experimental*/
} WavCompressionCode_t;

#endif /* WAV_CONST_H */
