$(info TRNG_X86_DRV_PRECONFIG_INC=  $(TRNG_X86_DRV_PRECONFIG_INC) )
ifneq ($(TRNG_X86_DRV_PRECONFIG_INC),Y)
    TRNG_X86_DRV_PRECONFIG_INC=Y
    # $(error  TRNG_X86_DRV_PRECONFIG )
    TRNG=Y
    MCAL=Y
    SECURITY=Y
    COMPUTING=Y
endif