#ifndef STM32F407VG_CONST_H
#define STM32F407VG_CONST_H

#include "macro_utils.h"

#define ADC_CHANNELS_COUNT 24
#define ADC_COUNT 3
#define AHB1_CLOCK_HZ SYS_FREQ
#define APB1_CLOCK_HZ (AHB1_CLOCK_HZ/4)
#define APB2_CLOCK_HZ (AHB1_CLOCK_HZ/2)
#define CAN_COUNT 2
#define CPU_MAX_HZ 168000000
#define DAC_COUNT 2
#define DMA_COUNT 2
#define DMA_STREAM_COUNT 8
#define DMA_CHANNEL_COUNT DMA_STREAM_COUNT
#define GPIO_COUNT 114
#define I2C_COUNT 3
#define GPIO_PIN_MAX 15
#define I2S_COUNT 2
#define LSI_FREQ 32000
#define MAX_IRQ_NUM 81 //  FPU_IRQn                    = 81      /*!< FPU global interrupt
#define MCU_NAME "stm32f407vg"
#define MCU_PACKAGE  "LQFP100"
#define RAM_END (RAM_START + RAM_SIZE)
#define RAM_SIZE (192 * K_BYTES)
#define RAM_START 0x20000000
#define ROM_END (ROM_START + ROM_SIZE)
#define ROM_SIZE (1024 * K_BYTES)
#define ROM_START 0x08000000
#define NOR_FLASH_START ROM_START
#define SDIO_COUNT 1
#define SPI_COUNT 3
#define SYS_FREQ 48000000
#define TIMER_COUNT 14
#define TRNG_COUNT 1
#define UART_COUNT 4
#define USB_COUNT 2
#define TIMER_MAX_NUM (TIMER_COUNT+1)
#define UART_MAX_NUM (UART_COUNT+1)

#define NOR_FLASH_END (ROM_END)
#define TIMER_MAX_COUNT (TIMER_COUNT+1)

#endif /* STM32F407VG_CONST_H */
