#ifndef C_GENERATOR_CONST_H
#define C_GENERATOR_CONST_H

#ifndef HAS_C_GENERATOR
#error "+HAS_C_GENERATOR"
#endif

#include "c_generator_dep.h"

#define C_GENERATOR_DRIVER_VERSION 2

typedef enum {
    FUN_NAME_PARSE_STATE_IDLE = 1,
    FUN_NAME_PARSE_STATE_TYPE = 2,
    FUN_NAME_PARSE_STATE_FUNCTION_NAME = 3,
    FUN_NAME_PARSE_STATE_ARGUMENT = 4,
    FUN_NAME_PARSE_STATE_FUNCTION_BODY = 5,

    FUN_NAME_PARSE_STATE_UNDEF = 0,
}FuncNameParseState_t;


typedef enum {
    FUN_NAME_PARSE_INPUT_SPACE= 1,  //  ' '
    FUN_NAME_PARSE_INPUT_LETTER = 2,   //   s d f g h
    FUN_NAME_PARSE_INPUT_STAR = 3,   //    *
    FUN_NAME_PARSE_INPUT_CLOSING_PARENTHESIS = 4,  // )
    FUN_NAME_PARSE_INPUT_SEMICOLON = 5,   // ;
    FUN_NAME_PARSE_INPUT_NEW_LINE = 6,    //  \n
    FUN_NAME_PARSE_INPUT_CARRIAGE_RETURN = 7,   // \r
    FUN_NAME_PARSE_INPUT_OPENING_BRACE=8,// {
    FUN_NAME_PARSE_INPUT_CLOSING_BRACE=9,//   }
    FUN_NAME_PARSE_INPUT_OPENING_PARENTHESIS = 10,  // (


    FUN_NAME_PARSE_INPUT_UNDEF = 0,
}FuncNameParseInput_t;


#endif /* C_GENERATOR_CONST_H */
