$(info ADC_CHANNEL_DRV_CUST_PRECFG_MK_INC=$(ADC_CHANNEL_DRV_CUST_PRECFG_MK_INC) )
ifneq ($(ADC_CHANNEL_DRV_CUST_PRECFG_MK_INC),Y)
    ADC_CHANNEL_DRV_CUST_PRECFG_MK_INC=Y

    ADC=Y
    ADC_CHANNEL=Y
    GPIO=Y
    SENSETIVITY=Y
    TIME=Y
endif