#ifndef FLASH_NRF5340_CONST_H
#define FLASH_NRF5340_CONST_H

#include "macro_utils.h"
#include "nrf5340_const.h"

#ifndef HAS_FLASH
#error "+HAS_FLASH"
#endif

#ifndef HAS_MICROCONTROLLER
#error "+HAS_MICROCONTROLLER"
#endif

#define QWORD_LEN 4

#define MAX_SINGLE_WRITE_SIZE 256

#ifdef HAS_CORE_APP
#define ON_CHIP_NOR_FLASH_START FLASH_START_APP_CORE
#define ON_CHIP_NOR_FLASH_SIZE (FLASH_SIZE_APP_CORE)
#define ON_CHIP_NOR_FLASH_PAGE_SIZE (ON_CHIP_NOR_FLASH_APP_PAGE_SIZE)
#endif /*HAS_CORE_APP*/

#ifdef HAS_CORE_NET
#define ON_CHIP_NOR_FLASH_START FLASH_START_NET_CORE
#define ON_CHIP_NOR_FLASH_SIZE (256*K_BYTES)
#define ON_CHIP_NOR_FLASH_PAGE_SIZE  (ON_CHIP_NOR_FLASH_NET_PAGE_SIZE)
#endif /*HAS_CORE_NET*/

#define ON_CHIP_NOR_FLASH_END (ON_CHIP_NOR_FLASH_START+ON_CHIP_NOR_FLASH_SIZE)
//#define FLASH_END_APP_CORE (FLASH_START_APP_CORE+FLASH_SIZE_APP_CORE)
#define FLASH_END_NET_CORE (FLASH_START_NET_CORE+FLASH_SIZE_NET_CORE)

#define ON_CHIP_NOR_FLASH_PAGE_CNT ((ON_CHIP_NOR_FLASH_SIZE)/(ON_CHIP_NOR_FLASH_PAGE_SIZE))

#endif /* FLASH_NRF5340_CONST_H  */
