$(info WATCHDOG_CUSTOM_PRE_CFG_MK_INC=$(WATCHDOG_CUSTOM_PRE_CFG_MK_INC) )
ifneq ($(WATCHDOG_CUSTOM_PRE_CFG_MK_INC),Y)
    WATCHDOG_CUSTOM_PRE_CFG_MK_INC=Y

    WATCHDOG_CUSTOM=Y
    WATCHDOG=Y
    IWDG=Y
endif


