$(info RV32IMC_PRECONFIG_MK_INC=$(RV32IMC_PRECONFIG_MK_INC) )
ifneq ($(RV32IMC_PRECONFIG_MK_INC),Y)
    RV32IMC_PRECONFIG_MK_INC=Y


    RV32IMC_DIR = $(CORE_DIR)/rv32imc

    ARM=Y
    RV32IMC=Y
    RISC_V=Y
    MICROCONTROLLER=Y
endif