#ifndef STM32F746G_DISCO_HW_CONFIG_H
#define STM32F746G_DISCO_HW_CONFIG_H

#define IO_LED_TX0    E, 13, MODE_OUTPUT_PP, NOPULL, SPEED_FREQ_MEDIUM, NOAF
#define IO_LED_RX0    E, 14, MODE_OUTPUT_PP, NOPULL, SPEED_FREQ_MEDIUM, NOAF

#define IO_LED_TX1    E, 13, MODE_OUTPUT_PP, NOPULL, SPEED_FREQ_MEDIUM, NOAF
#define IO_LED_RX1    E, 14, MODE_OUTPUT_PP, NOPULL, SPEED_FREQ_MEDIUM, NOAF

#define IO_LED_STAT   E, 15, MODE_OUTPUT_PP, NOPULL, SPEED_FREQ_MEDIUM, NOAF

#define CAN1_RX       D, 0, MODE_AF_PP, PULLUP, SPEED_FREQ_VERY_HIGH, AF9_CAN1
#define CAN1_TX       D, 1, MODE_AF_PP, NOPULL, SPEED_FREQ_VERY_HIGH, AF9_CAN1

#define CAN2_RX       B, 5, MODE_AF_PP, PULLUP, SPEED_FREQ_VERY_HIGH, AF9_CAN2
#define CAN2_TX       B, 6, MODE_AF_PP, NOPULL, SPEED_FREQ_VERY_HIGH, AF9_CAN2

#define IO_LED_HI     PIN_HI
#define IO_LED_LOW    PIN_LOW

#endif /* STM32F746G_DISCO_HW_CONFIG_H  */


