$(info CLI_CONFIG_MK_INC=$(CLI_CONFIG_MK_INC) )
ifneq ($(CLI_CONFIG_MK_INC),Y)
    CLI_CONFIG_MK_INC=Y
    
    CONNECTIVITY_COMMANDS=Y
    STORAGE_COMMANDS=Y
    CORE_COMMANDS=Y
    FLASH_COMMANDS=Y
    BOOTLOADER_COMMANDS=Y
    CORTEX_M4_COMMANDS=N
    IWDG_COMMANDS=N
    UART_COMMANDS=N
    SYSTEM_COMMANDS=N
    BOOTLOADER_COMMANDS=N
    SW_COMPONENT_COMMANDS=N
    INTERRUPT_COMMANDS=N
    SCHEDULER_COMMANDS=N
    # include $(WORKSPACE_LOC)cli_bootloader.mk

endif