$(info CORTEX_M7_PRECONFIG_MK_INC=$(CORTEX_M7_PRECONFIG_MK_INC) )
ifneq ($(CORTEX_M7_PRECONFIG_MK_INC),Y)
    CORTEX_M7_PRECONFIG_MK_INC=Y


    CORTEX_M7_DIR = $(CORE_DIR)/cortex_m7

    ARM=Y
    CORTEX_M7=Y
    CORTEX_M=Y
    MICROCONTROLLER=Y
endif