#ifndef SW_UART_CONST_H
#define SW_UART_CONST_H

#include "time_mcal.h"
#include "sw_uart_dep.h"

#define SW_UART_VERSION "3"
#define SW_UART_PERIOD_US 1
#define SW_UART_MAX_SAMPLE_PER_BIT 16

#define SW_UART_PARITY_BIT_CNT (1)
#define SW_UART_START_BIT_CNT (1)
#define SW_UART_STOP_BIT_CNT (2)
#define SW_UART_DATA_BIT_CNT (8)

#define SW_UART_BIT_PER_FRAME_PN_D8_S1 (1+8+1)
#define SW_UART_BIT_PER_FRAME_PN_D8_S2 (1+8+2)
#define SW_UART_BIT_PER_FRAME_MAX ( 1 + 8 + 1 + 2 )

#define SW_UART_BIT_PER_FRAME (SW_UART_START_BIT_CNT+SW_UART_DATA_BIT_CNT+SW_UART_PARITY_BIT_CNT+SW_UART_STOP_BIT_CNT)
#define SW_UART_SAMPLE_PER_FRAME (SW_UART_BIT_PER_FRAME_MAX*SW_UART_MAX_SAMPLE_PER_BIT)

typedef enum {
    SW_UART_RX_ACTION_UNDEF,
    SW_UART_RX_ACTION_PROC_DONE,
    SW_UART_RX_ACTION_PROC1,
    SW_UART_RX_ACTION_PROC2
}SwUartRxAction_t;

typedef enum {
    SW_UART_RX_FRAME_STATE_UNDEF=0,
    SW_UART_RX_FRAME_STATE_IDLE=1,
    SW_UART_RX_FRAME_STATE_REC=2
}SwUartRxFrameState_t;


typedef enum {
    SW_UART_PARITY_UNDEF = 0,
    SW_UART_PARITY_NONE,
    SW_UART_PARITY_ODD, // 1 3 5 7
    SW_UART_PARITY_EVEN, // 2 4 6 8
} SwUartParity_t;



#endif /* SW_UART_CONST_H */
