$(info DUMMY_BOARD_PRECONFIG_MK_INC=$(DUMMY_BOARD_PRECONFIG_MK_INC))
ifneq ($(DUMMY_BOARD_PRECONFIG_MK_INC),Y)
    DUMMY_BOARD_PRECONFIG_MK_INC=Y

    #@echo $(error ASICS=$(ASICS))
    
    ASICS=Y
    DUMMY_BOARD=Y
    FC7300F8MDT=Y
    MICROCONTROLLER=Y
endif
