ifneq ($(LOOPBACK_AUDIO_PRECONFIG_INC),Y)
    LOOPBACK_AUDIO_PRECONFIG_INC=Y

    LOOPBACK_AUDIO=Y
    SOUND_RECORDER=Y
    I2S=Y
    WAV_PLAYER=Y
    WAV=Y
    LED=Y
    WAV_PLAYER_INTERRUPTS=N
endif
