#ifndef LOOPBACK_AUDIO_CONST_H
#define LOOPBACK_AUDIO_CONST_H

#include "time_mcal.h"
#include "loopback_audio_dep.h"

#define LOOPBACK_AUDIO_VERSION 1
#define LOOPBACK_AUDIO_PERIOD_US 1

typedef enum {
    LOOPBACK_AUDIO_INPUT_UNDEF = 0,
    LOOPBACK_AUDIO_INPUT_TX_HALF,
    LOOPBACK_AUDIO_INPUT_TX_DONE,
    LOOPBACK_AUDIO_INPUT_RX_HALF,
    LOOPBACK_AUDIO_INPUT_RX_DONE,
}LoopbackAudioInput_t;

typedef enum {
    LOOPBACK_AUDIO_STATE_UNDEF = 0,
    LOOPBACK_AUDIO_STATE_PLAY1 ,
    LOOPBACK_AUDIO_STATE_PLAY2 ,
    LOOPBACK_AUDIO_STATE_PLAY2_REC1 ,
    LOOPBACK_AUDIO_STATE_PLAY1_REC2 ,
    LOOPBACK_AUDIO_STATE_REC1 ,
    LOOPBACK_AUDIO_STATE_REC2 ,
}LoopbackAudioState_t;

typedef enum {
    LOOPBACK_ACTION_UNDEF = 0 ,
    LOOPBACK_ACTION_LOAD1  ,
    LOOPBACK_ACTION_LOAD2  ,

    LOOPBACK_ACTION_SAVE1  ,
    LOOPBACK_ACTION_SAVE2  ,

    LOOPBACK_ACTION_SAVE1_LOAD2  ,
    LOOPBACK_ACTION_SAVE2_LOAD1  ,

}LoopbackAudioAction_t;


#endif /* LOOPBACK_AUDIO_CONST_H */
