
$(info EEPROM_PRESET_MCAL_MK_INC=$(EEPROM_PRESET_MCAL_MK_INC))
ifneq ($(EEPROM_PRESET_MCAL_MK_INC),Y)
    EEPROM_PRESET_MCAL_MK_INC=Y
    EEPROM=Y
    CRC16=Y
    MICROCONTROLLER=Y

    ifeq ($(EEPROM_WRITE),Y)
        WRITE_ADDR=Y
    endif
endif


