$(info DAC_CHANNEL_DRV_CUST_PRECFG_MK_INC=$(DAC_DRV_CUST_PRECFG_MK_INC) )
ifneq ($(DAC_CHANNEL_DRV_CUST_PRECFG_MK_INC),Y)
    DAC_CHANNEL_DRV_CUST_PRECFG_MK_INC=Y

    DAC=Y
    DAC_CHANNEL=Y
    GPIO=Y
    TIME=Y
endif