#ifndef INDEPANDENT_WATCHDOG_CONST_H
#define INDEPANDENT_WATCHDOG_CONST_H

#include "sys_config.h"
#include "timer_utils.h"

#define WATCHDOG_TIMEOUT_MS 10000
#define WATCHDOG_POLL_PERIOD_US MSEC_2_USEC(100)

typedef enum{
    WATCHDOG_KEY_UNLOCK= 0x1E,
    WATCHDOG_KEY_LAUNCH_REFRESH= 0x71,
    WATCHDOG_KEY_STOP= 0xE8,
    WATCHDOG_KEY_UNDEF = 0,
}WatchDogKey_t;


typedef enum{
    MIK32_WATCH_DOG_PRE_SCALE_DIV_1  =0 ,
    MIK32_WATCH_DOG_PRE_SCALE_DIV_2  =1 ,
    MIK32_WATCH_DOG_PRE_SCALE_DIV_4  = 2,
    MIK32_WATCH_DOG_PRE_SCALE_DIV_16  = 3,
    MIK32_WATCH_DOG_PRE_SCALE_DIV_64  = 4,
    MIK32_WATCH_DOG_PRE_SCALE_DIV_256  = 5,
    MIK32_WATCH_DOG_PRE_SCALE_DIV_1024  = 6,
    MIK32_WATCH_DOG_PRE_SCALE_DIV_4096  = 7,
	MIK32_WATCH_DOG_PRE_SCALE_UDEF = 8,
}Mik32WatchDogPreScale_t;





#define PRESCALER_VAL_MAX 4096
#define RELOAD_VAL_MAX 4095

#endif /* INDEPANDENT_WATCHDOG_CONST_H  */
