#ifndef FLASH_MCAL_CONST_H
#define FLASH_MCAL_CONST_H

#include "flash_dep.h"

typedef enum {
    MEM_CONTENT_MBR = 0,
    MEM_CONTENT_FLASH_FS_PAGE1 = 1,
    MEM_CONTENT_FLASH_FS_PAGE2 = 2,
    MEM_CONTENT_GENERIC = 3,
    MEM_CONTENT_BOOTLADER = 4,
    MEM_CONTENT_GENERIC_APP = 5,
    MEM_CONTENT_GENERIC_NET = 6,
    MEM_CONTENT_CONFIG = 7,
    MEM_CONTENT_UNDEF = 8,
} MemContent_t;

typedef enum {
    FLASH_OPERATION_NOPE = 1,
    FLASH_OPERATION_PROGRAM_BYTE = 8,
    FLASH_OPERATION_PROGRAM_WORD = 16,
    FLASH_OPERATION_PROGRAM_QWORD = 32,
    FLASH_OPERATION_ERRASE = 256,
    FLASH_OPERATION_ERRASE_SECTOR = 64,
    FLASH_OPERATION_ERRASE_BLOCK = 33,
    FLASH_OPERATION_ERRASE_SYS_DATA_AREA = 34,
    FLASH_OPERATION_ERRASE_MASS = 35,
    FLASH_OPERATION_UNDEF = 0
}FlashOperation_t;

typedef enum {
    FLASH_STATE_IDLE = 1,
    FLASH_STATE_WAIT_END_OF_OPERATION = 2,
    FLASH_STATE_WAIT_END_OF_WRITE = 3,
    FLASH_STATE_WAIT_END_OF_ERASE = 4,
    FLASH_STATE_UNDEF = 0
}FlashState_t;

typedef enum {
    FLASH_INPUT_NONE = 10,
    FLASH_INPUT_OPERATION_BUSY = 1,
    FLASH_INPUT_NO_OPERATION = 6,
    FLASH_INPUT_PROGRAMMING_ERROR = 2,
    FLASH_INPUT_ERASE_PROGRAM_PROTECTION_ERROR = 4,
    FLASH_INPUT_OPERATION_DONE = 5,
    FLASH_INPUT_TIMEOUT = 3,
    FLASH_INPUT_UNDEF = 0
}FlashInput_t;

#endif /* FLASH_MCAL_CONST_H */
