
$(info FLASH_PRESET_MCAL_MK_INC=$(FLASH_PRESET_MCAL_MK_INC))
ifneq ($(FLASH_PRESET_MCAL_MK_INC),Y)
    FLASH_PRESET_MCAL_MK_INC=Y
    FLASH=Y
    #CRC16=Y
    FLOAT=Y
    ARRAY=Y
    STORAGE=Y
    MICROCONTROLLER=Y
    DEBUGGER=Y

    ifeq ($(FLASH_WRITE),Y)
        WRITE_ADDR=Y
    endif
endif
