$(info TEST_WAV_PLAYER_MK_INC=$(TEST_WAV_PLAYER_MK_INC))

ifneq ($(TEST_WAV_PLAYER_MK_INC),Y)
    TEST_WAV_PLAYER_MK_INC=Y

    TEST_WAV_PLAYER_DIR = $(TEST_SET_SW_DIR)/test_wav_player
    #@ $(error TEST_WAV_PLAYER_DIR= $(TEST_WAV_PLAYER_DIR))

    MCAL_OPT += -DHAS_TEST_SUIT_WAV_PLAYER
    MCAL_OPT += -DHAS_TEST_WAV_PLAYER
    INCDIR  += -I$(TEST_WAV_PLAYER_DIR)

    SOURCES_C += $(TEST_WAV_PLAYER_DIR)/test_wav_player.c
endif
