$(info Flash Stm32 MCU Script)

FIRMWARE_BINARY_FILE=$(BUILD_DIR)\$(TARGET).hex
VENDOR_FLASH_CLI_TOOL=ST-LINK_CLI.exe

VENDOR_FLASH_CLI_OPTIONS=
VENDOR_FLASH_CLI_OPTIONS +=  -c
VENDOR_FLASH_CLI_OPTIONS += JTAG freq=4000 HOTPLUG 
VENDOR_FLASH_CLI_OPTIONS += LPM
VENDOR_FLASH_CLI_OPTIONS += -P $(FIRMWARE_BINARY_FILE) 
VENDOR_FLASH_CLI_OPTIONS += -V "after_programming"
VENDOR_FLASH_CLI_OPTIONS += -Log -TVolt

.PHONY: flash_stm32
flash_stm32: $(FIRMWARE_BINARY_FILE)
	$(info Flash File:$(FIRMWARE_BINARY_FILE) ...)
	$(VENDOR_FLASH_CLI_TOOL) $(VENDOR_FLASH_CLI_OPTIONS)
	$(info FlashArteryMCUTargetDone)
	$(VENDOR_FLASH_CLI_TOOL) -Rst

