
ifneq ($(ORTHODOX_CANONICAL_FIRMWARE_MK),Y)
    ORTHODOX_CANONICAL_FIRMWARE_MK=Y

    # $(error ORTHODOX_CANONICAL_FIRMWARE_MK=$(ORTHODOX_CANONICAL_FIRMWARE_MK))

    ORTHODOX_CANONICAL_FIRMWARE=Y
    TIME=Y
    CONTROL=Y
    NORTOS=Y
    SUPER_CYCLE=Y
    FIRMWARE=Y
    CORE=Y
    TERMINAL=Y
    MCAL=Y
    TASK=Y
    BOARD=Y
    GENERIC=Y
    MICROCONTROLLER=Y
    TIMER=Y
    GPIO=Y
    CLI=Y
    LED=Y
    UART=Y
endif
