#ifndef DIAGNOSTIC_PAGE_NUMS_H
#define DIAGNOSTIC_PAGE_NUMS_H

#define DIAG_PAGE_INDEX (0u)
#define DIAG_PAGE_VERSION (1u)
#define DIAG_PAGE_CAN (2U)
#define DIAG_PAGE_MODEL (4U)
#define DIAG_PAGE_SYSINFO (5u)
#define DIAG_PAGE_TASKS (6u)
#define DIAG_PAGE_UARTS (7u)
#define DIAG_PAGE_PARAMS (8u)
#define DIAG_PAGE_ADC (9u)
#define DIAG_PAGE_TEMP_SENSOR (11u)
#define DIAG_PAGE_GPIO_STATE 40U
#define DIAG_PAGE_GPIO_LIST 41U

#endif /* DIAGNOSTIC_PAGE_NUMS_H */
