#ifndef SX1262_OP_CODES_H
#define SX1262_OP_CODES_H
 
/*Operational Modes Commands*/
#define OPCODE_RESET_STATS 0x00
#define OPCODE_CLEAR_IRQ_STATUS 0x02
#define OPCODE_CLEAR_DEVICE_ERRORS 0x07
#define OPCODE_SET_DIO_IRQ_PARAMS 0x08
#define OPCODE_WRITE_REGISTER 0x0D
#define OPCODE_WRITE_BUFFER 0x0E
#define OPCODE_GET_STATS 0x10
#define OPCODE_GET_PACKET_TYPE 0x11
#define OPCODE_GET_IRQ_STATUS 0x12
#define OPCODE_GET_RX_BUFFER_STATUS 0x13
#define OPCODE_GET_PACKET_STATUS 0x14
#define OPCODE_GET_RSSIINST 0x15
#define OPCODE_GET_DEVICE_ERRORS 0x17
#define OPCODE_READ_REGISTER 0x1D
#define OPCODE_READ_BUFFER 0x1E
#define OPCODE_SET_STANDBY 0x80
#define OPCODE_SET_RX 0x82
#define OPCODE_SET_TX 0x83
#define OPCODE_SET_SLEEP 0x84
#define OPCODE_SET_RF_FREQUENCY 0x86
#define OPCODE_SET_CAD_PARAM 0x88
#define OPCODE_CALIBRATE 0x89
#define OPCODE_SET_PACKET_TYPE 0x8A
#define OPCODE_SET_MODULATION_PARAMS 0x8b
#define OPCODE_SET_PACKET_PARAMS 0x8C
#define OPCODE_SET_TX_PARAMS 0x8E
#define OPCODE_SET_BUFFER_BASE_ADDR 0x8F
#define OPCODE_SET_FALLBACK_MODE 0x93
#define OPCODE_SET_RX_DUTY_CYCLE 0x94
#define OPCODE_SET_PA_CONFIG 0x95
#define OPCODE_SET_REGULATOR_MODE 0x96
#define OPCODE_SET_DIO3_AS_TCXO_CTRL 0x97
#define OPCODE_CALIBRATE_IMAGE 0x98
#define OPCODE_SET_DIO2_AS_RFSWITCH 0x9d
#define OPCODE_STOP_TIMER_ON_PREAMBLE 0x9f
#define OPCODE_SET_LORA_SYMBOL_TIMEOUT 0xa0
#define OPCODE_GET_STATUS 0xC0
#define OPCODE_SET_FS 0xc1
#define OPCODE_SET_CAD 0xC5
#define OPCODE_SET_TX_CARRIER 0xD1
#define OPCODE_SET_TX_PREAMBLE 0xd2

 
#endif /* SX1262_OP_CODES_H  */
