$(info CORTEX_M33_PRECONFIG_MK_INC=$(CORTEX_M33_PRECONFIG_MK_INC) )
ifneq ($(CORTEX_M33_PRECONFIG_MK_INC),Y)
    CORTEX_M33_PRECONFIG_MK_INC=Y

    CORTEX_M33_DIR = $(CORE_DIR)/cortex_m33

    MICROCONTROLLER=Y
    CORTEX_M33=Y
    ARM=Y
    NVIC=Y
    # SYSTICK=Y

endif