
$(info WATCHDOG_PRECONFIG_INC=$(WATCHDOG_PRECONFIG_INC) )
ifneq ($(WATCHDOG_PRECONFIG_INC),Y)
    WATCHDOG_PRECONFIG_INC=Y

    WATCHDOG_MCAL_DIR = $(MCAL_COMMON_DIR)/watchdog
    #@echo $(error WATCHDOG_MCAL_DIR=$(WATCHDOG_MCAL_DIR))

    WATCHDOG=Y
    MICROCONTROLLER=Y

endif