$(info TEST_PYRAMID_ACCEL_CALIB_MK_INC=$(TEST_PYRAMID_ACCEL_CALIB_MK_INC))

ifneq ($(TEST_PYRAMID_ACCEL_CALIB_MK_INC),Y)
    TEST_PYRAMID_ACCEL_CALIB_MK_INC=Y

    TEST_PYRAMID_ACCEL_CALIB_DIR = $(TEST_SET_SW_DIR)/test_pyramid_accel_calib
    #@echo $(error TEST_PYRAMID_ACCEL_CALIB_DIR= $(TEST_PYRAMID_ACCEL_CALIB_DIR))

    OPT += -DHAS_TEST_SUIT_PYRAMID_ACCEL_CALIB
    OPT += -DHAS_TEST_PYRAMID_ACCEL_CALIB
    INCDIR  += -I$(TEST_PYRAMID_ACCEL_CALIB_DIR)

    SOURCES_C += $(TEST_PYRAMID_ACCEL_CALIB_DIR)/test_pyramid_accel_calib.c
endif
