#include "interrupt_config.h"

//#include "sys_config.h"
#ifdef HAS_DATA_MISC
#include "data_utils.h"
#endif

#define  INTERRUPT_CONFIG_ADC

#define  INTERRUPT_CONFIG_DMA




#define INTERRUPT_CONFIG_UART


#define INTERRUPT_CONFIG_TMR_CH


#define INTERRUPT_CONFIG_TIMER0


#define INTERRUPT_CONFIG_TIMER1

#define INTERRUPT_CONFIG_TIMER2

#define INTERRUPT_CONFIG_TIMER5


#define INTERRUPT_CONFIG_TIMER4


#define INTERRUPT_CONFIG_TIMER3

#define INTERRUPT_CONFIG_TIMER    \
    INTERRUPT_CONFIG_TMR_CH  \
    INTERRUPT_CONFIG_TIMER0   \
    INTERRUPT_CONFIG_TIMER1   \
    INTERRUPT_CONFIG_TIMER2   \
    INTERRUPT_CONFIG_TIMER3   \
    INTERRUPT_CONFIG_TIMER4   \
    INTERRUPT_CONFIG_TIMER5




#define INTERRUPT_CONFIG_CAN0

#define INTERRUPT_CONFIG_CAN1

#define INTERRUPT_CONFIG_CAN2

#define INTERRUPT_CONFIG_CAN3

#define INTERRUPT_CONFIG_CAN4

#define INTERRUPT_CONFIG_CAN5

#define INTERRUPT_CONFIG_CAN6

#define INTERRUPT_CONFIG_CAN7

#define INTERRUPT_CONFIG_CAN8

#define INTERRUPT_CONFIG_CAN9


#define INTERRUPT_CONFIG__CAN   \
    INTERRUPT_CONFIG_CAN0  \
    INTERRUPT_CONFIG_CAN1  \
    INTERRUPT_CONFIG_CAN2  \
    INTERRUPT_CONFIG_CAN3  \
    INTERRUPT_CONFIG_CAN4  \
    INTERRUPT_CONFIG_CAN5  \
    INTERRUPT_CONFIG_CAN6  \
    INTERRUPT_CONFIG_CAN7  \
    INTERRUPT_CONFIG_CAN8  \
    INTERRUPT_CONFIG_CAN9




#define INTERRUPT_CONFIG_I2C


#define INTERRUPT_CONFIG_GPIO

#define INTERRUPT_CONFIG_SPI0

#define INTERRUPT_CONFIG_SPI1

#define INTERRUPT_CONFIG_SPI2

#define INTERRUPT_CONFIG_SPI3

#define INTERRUPT_CONFIG_SPI4

#define INTERRUPT_CONFIG_SPI5

#define INTERRUPT_CONFIG_SPI6

#define INTERRUPT_CONFIG_SPI7

#define INTERRUPT_CONFIG_SPI        \
    INTERRUPT_CONFIG_SPI0           \
    INTERRUPT_CONFIG_SPI1           \
    INTERRUPT_CONFIG_SPI2           \
    INTERRUPT_CONFIG_SPI3           \
    INTERRUPT_CONFIG_SPI4           \
    INTERRUPT_CONFIG_SPI5           \
    INTERRUPT_CONFIG_SPI6           \
    INTERRUPT_CONFIG_SPI7


#define INTERRUPT_CONFIG_INTERFACES    \
   INTERRUPT_CONFIG__CAN                \
   INTERRUPT_CONFIG_I2C                \
   INTERRUPT_CONFIG_SPI                \
   INTERRUPT_CONFIG_UART

#define INTERRUPT_CONFIG_RESERVED


#define INTERRUPT_CONFIG_MAM0

#define INTERRUPT_CONFIG_MAM1

#define INTERRUPT_CONFIG_MAM2



#define INTERRUPT_CONFIG_MAM        \
    INTERRUPT_CONFIG_MAM0           \
    INTERRUPT_CONFIG_MAM1           \
    INTERRUPT_CONFIG_MAM2


const InterruptConfig_t InterruptConfig[] ={
   INTERRUPT_CONFIG_INTERFACES \
   INTERRUPT_CONFIG_DMA \
   INTERRUPT_CONFIG_MAM \
   INTERRUPT_CONFIG_ADC \
   INTERRUPT_CONFIG_GPIO \
   INTERRUPT_CONFIG_RESERVED \
   INTERRUPT_CONFIG_TIMER

};


uint32_t interrupt_get_cnt(void) {
    uint32_t cnt = 0;
    cnt = ARRAY_SIZE(InterruptConfig);
    return cnt;

}
