$(info SLIDING_INTEGRAL_PRECONFIG_INC=$(SLIDING_INTEGRAL_PRECONFIG_INC) )

ifneq ($(SLIDING_INTEGRAL_PRECONFIG_INC),Y)
    SLIDING_INTEGRAL_PRECONFIG_INC=Y

    SLIDING_INTEGRAL=Y
    CIRCULAR_BUFFER=Y
    DSP=Y
endif
