#ifndef GRAPHVIZ_TO_TSORT_CONST_H
#define GRAPHVIZ_TO_TSORT_CONST_H

#ifndef HAS_GRAPHVIZ_TO_TSORT
#error "+HAS_GRAPHVIZ_TO_TSORT"
#endif

#include "time_mcal.h"

#include "graphviz_to_tsort_dep.h"

#define MAX_COMP_CNT 100
#define DEP_CSV_SIZE 500
#define TOKEN_SIZE 80
#define GRAPHVIZ_TO_TSORT_DRIVER_VERSION 1

typedef enum {
    GRA_TSORT_STATE_UNDEF=0,
    GRA_TSORT_STATE_IDLE=1,
    GRA_TSORT_STATE_SOURCE=2,
    GRA_TSORT_STATE_WAIT_ARROW=3,
    GRA_TSORT_STATE_RX_ARROW=4,
    GRA_TSORT_STATE_DESTINATION=5,
    GRA_TSORT_STATE_LINE_DONE=6,
}GraTsortState_t;

typedef enum{
    GRA_TSORT_INPUT_UNDEF=0,
    GRA_TSORT_INPUT_LETTER=1,
    GRA_TSORT_INPUT_DASH=2,
    GRA_TSORT_INPUT_RIGHT_ARROW=3,
    GRA_TSORT_INPUT_END_OF_LINE=4,
    GRA_TSORT_INPUT_SPACE=5,
    GRA_TSORT_INPUT_REST=6,
}GraTsortInput_t;

#endif /* GRAPHVIZ_TO_TSORT_CONST_H */
