$(info DASHBOARD_PRECONFIG=$(DASHBOARD_PRECONFIG))

ifneq ($(DASHBOARD_PRECONFIG),Y)
    DASHBOARD_DRV_MK_LOG=Y

    DASHBOARD_DRV_DIR = $(APPLICATIONS_DIR)/dashboard

    DASHBOARD=Y
    TIME=Y
    RUNNING_LINE=Y
    #I2C=Y
    #SSD1306=Y
endif