#ifndef INTERFACES_CONST_H
#define INTERFACES_CONST_H

/*for I2S SPI MDIO I2C MII PDM SDIO 1wire*/
typedef enum {
    BUS_ROLE_MASTER = 1,
    BUS_ROLE_SLAVE = 2,

    BUS_ROLE_UNDEF = 0,
} IfBusRole_t;


typedef enum {
    INTERFACE_NAME_UNDEF = 0,
    INTERFACE_NAME_UART=1 ,
    INTERFACE_NAME_CAN= 2 ,
    INTERFACE_NAME_SDIO =3,
    INTERFACE_NAME_SERIAL_PORT =4,
    INTERFACE_NAME_RS485 = 5,
    INTERFACE_NAME_UWB = 6,
    INTERFACE_NAME_WIFI = 7,
    INTERFACE_NAME_RS232 = 8 ,
    INTERFACE_NAME_LORA = 9,
    INTERFACE_NAME_GFSK = 10,
    INTERFACE_NAME_CAN_FD = 11,
    INTERFACE_NAME_LOOPBACK=12 ,
    INTERFACE_NAME_STDIO = 13 ,
    INTERFACE_NAME_BLACKHOLE = 14,
    INTERFACE_NAME_BLUETOOTH  = 15 ,
    INTERFACE_NAME_SPI =16,
    INTERFACE_NAME_I2C=17 ,
    INTERFACE_NAME_LIN =18,
    INTERFACE_NAME_I2S =19,
    INTERFACE_NAME_USB=20,
    INTERFACE_NAME_1_WIRE=21 ,
    INTERFACE_NAME_BLE = 22,
    INTERFACE_NAME_ISO_TP = 23,
    INTERFACE_NAME_RAM = 24,
    INTERFACE_NAME_FLASH = 25,
    INTERFACE_NAME_NVRAM = 26,
    INTERFACE_NAME_ESP_01 = 27,
    INTERFACE_NAME_SEGGER_RTT = 28,
    INTERFACE_NAME_RS422,
    INTERFACE_NAME_IR,
    INTERFACE_NAME_ISO7816,
    INTERFACE_NAME_PDM ,
    INTERFACE_NAME_HDMI,
    INTERFACE_NAME_PWM ,
    INTERFACE_NAME_PCI,
    INTERFACE_NAME_MII ,
    INTERFACE_NAME_RMII,
    INTERFACE_NAME_SMBUS ,
    INTERFACE_NAME_GMII,
    INTERFACE_NAME_SWD,
    INTERFACE_NAME_DDR3,
    INTERFACE_NAME_DDR4,
    INTERFACE_NAME_JTAG,
    INTERFACE_NAME_MDIO,
    INTERFACE_NAME_NFC,
    INTERFACE_NAME_RFID,
    INTERFACE_NAME_LVDS ,
    INTERFACE_NAME_CNT ,
} InterfaceName_t;



/*
 for SPI, I2S
 Some microcontrollers (FC7300x ) do not have separate interrupts for receiving or transmitting.
 Just one move-done interrupt.
 There you need to explicitly indicate to the interrupt what is happening by bypassing a RAM variable.
 */
typedef enum {
    INTERFACE_OPERATION_IDLE = 1,
    INTERFACE_OPERATION_RECEPTION = 2,  /*RX*/
    INTERFACE_OPERATION_SEND = 3,       /*TX*/
    INTERFACE_OPERATION_RECEPTION_AND_TRANSMISSION = 4,  /*TXRX*/
    INTERFACE_OPERATION_UNDEF = 0,
} IfOperation_t;


typedef enum {
    RETX_NO_NEED = 0,
    RETX_NEED = 1,
} IfRetx_t;

//
typedef enum {
    BIT_ORDER_MSB = 1,
    BIT_ORDER_LSB = 2,

    BIT_ORDER_UNDEF = 0,
} IfBitOrder_t;



#endif /* INTERFACES_CONST_H */
