
TEST_PROTOCOL_DIR = $(TEST_SET_SW_DIR)/test_protocol
#@echo $(error TEST_PROTOCOL_DIR= $(TEST_PROTOCOL_DIR))
#@echo $(error CFLAGS= $(CFLAGS))
OPT += -DHAS_TEST_SUIT_PROTOCOL
OPT += -DHAS_TEST_PROTOCOL

INCDIR += -I$(TEST_PROTOCOL_DIR)

SOURCES_C += $(TEST_PROTOCOL_DIR)/test_protocol.c