$(info CAN_COMMON_MCAL_PRECONFIG_INC=$(CAN_COMMON_MCAL_PRECONFIG_INC) )

ifneq ($(CAN_COMMON_MCAL_PRECONFIG_INC),Y)
    CAN_COMMON_MCAL_PRECONFIG_INC=Y
    CAN=Y
    GPIO=Y
    MCAL=Y
    INTERFACES=Y
    CONNECTIVITY=Y

endif



