#ifndef MAILBOX_GENERAL_CONST_H
#define MAILBOX_GENERAL_CONST_H

#include "mailbox_dep.h"

#define MAILBOX_COMPONENT_VERSION "1"
#define MAILBOX_POLL_PERIOD_US 10
#define MAILBOX_TAKE_TIMEOUT_MS 2000
#define MAILBOX_CHANNEL_POLL_PERIOD_US 10

//#define MAILBOX_NUM 1

typedef enum {
    MAIL_BOX_CHANNEL_0 = 0,
    MAIL_BOX_CHANNEL_1 = 1,
    MAIL_BOX_CHANNEL_2 = 2,
    MAIL_BOX_CHANNEL_3 = 3,
    MAIL_BOX_CHANNEL_4 = 4  ,
    MAIL_BOX_CHANNEL_5 = 5  ,
    MAIL_BOX_CHANNEL_6 = 6  ,
    MAIL_BOX_CHANNEL_7 = 7  ,
    MAIL_BOX_CHANNEL_8 = 8  ,
    MAIL_BOX_CHANNEL_9 = 9  ,
    MAIL_BOX_CHANNEL_10 = 10,
    MAIL_BOX_CHANNEL_11 = 11,
    MAIL_BOX_CHANNEL_12 = 12,
    MAIL_BOX_CHANNEL_13 = 13,
    MAIL_BOX_CHANNEL_14 = 14,
    MAIL_BOX_CHANNEL_15 = 15,

    MAIL_BOX_CHANNEL_UNDEF = 255,
}MailBoxChannel_t;

#endif /* MAILBOX_GENERAL_CONST_H */
