$(info AUTO_BRIGHTNESS_PRECONFIG=$(AUTO_BRIGHTNESS_PRECONFIG))

ifneq ($(AUTO_BRIGHTNESS_PRECONFIG),Y)
    AUTO_BRIGHTNESS_DRV_MK_LOG=Y

    AUTO_BRIGHTNESS_DRV_DIR = $(APPLICATIONS_DIR)/auto_brightness

    AUTO_BRIGHTNESS=Y
    DISTANCE=Y
    PWM=Y

endif