$(info BLACK_BOX_PRECONFIG=$(BLACK_BOX_PRECONFIG))

ifneq ($(BLACK_BOX_PRECONFIG),Y)
    BLACK_BOX_DRV_MK_LOG=Y

    BLACK_BOX_DRV_DIR = $(APPLICATIONS_DIR)/black_box
 
    STORAGE=Y
    BLACK_BOX=Y
    FAT_FS=Y
endif