$(info PHASE_DETECTOR_PRECONFIG_INC=$(PHASE_DETECTOR_PRECONFIG_INC) )

ifneq ($(PHASE_DETECTOR_PRECONFIG_INC),Y)
    PHASE_DETECTOR_PRECONFIG_INC=Y

    PHASE_DETECTOR=Y
    CIRCULAR_BUFFER=Y
    COMPLEX=Y
    DFT=Y
    DSP=Y

endif
