ifneq ($(COMPILER_MK_INC),Y)
    COMPILER_MK_INC=Y

    MCAL_OPT += -DHAS_COMPILER
    COMPILER_DIR = $(WORKSPACE_LOC)/compiler
    # $(error COMPILER_DIR= $(COMPILER_DIR))

    MCAL_OPT += -DHAS_GCC
    INCDIR += -I$(COMPILER_DIR)
endif