#ifndef AUTO_VERSION_H
#define AUTO_VERSION_H

#define SUCCESSFUL_BUILD_COUNTER 297

#define GIT_BRANCH  "GIT_BRANCH_AUTO_REPLACE"
#define GIT_LAST_COMMIT_HASH  "GIT_LAST_COMMIT_HASH_AUTO_REPLACE"

#endif /*AUTO_VERSION_H*/
