$(info UART_CUSTOM_PRECONFIG_MK_INC=  $(UART_CUSTOM_PRECONFIG_MK_INC) )
ifneq ($(UART_CUSTOM_PRECONFIG_MK_INC),Y)
    UART_CUSTOM_PRECONFIG_MK_INC=Y

    HAL_DMA=Y
    #TIME=Y
    UART=Y
    GPIO=Y
endif