#ifndef FLASH_AT32_CONST_H
#define FLASH_AT32_CONST_H

#define QWORD_LEN 4

#ifndef HAS_MICROCONTROLLER
#error "+HAS_MICROCONTROLLER"
#endif

#define FLASH_WR_TIME_MS 20
#define MAX_SINGLE_WRITE_SIZE 256
#define FLASH_PAGE_CNT (NOR_FLASH_SIZE / FLASH_SECTOR_SIZE)

#endif /* FLASH_AT32_CONST_H  */
