
$(info TEST_AUTO_VOLUME_MK_INC=$(TEST_AUTO_VOLUME_MK_INC))

ifneq ($(TEST_AUTO_VOLUME_MK_INC),Y)
    TEST_AUTO_VOLUME_MK_INC=Y

    TEST_AUTO_VOLUME_DIR = $(TEST_SET_HW_DIR)/test_auto_volume
    #@echo $(error TEST_AUTO_VOLUME_DIR=$(TEST_AUTO_VOLUME_DIR))
    INCDIR += -I$(TEST_AUTO_VOLUME_DIR)
    OPT += -DHAS_TEST_AUTO_VOLUME
    SOURCES_C += $(TEST_AUTO_VOLUME_DIR)/test_auto_volume.c
endif