#ifndef STACK_FRAME_CONSTANTS_H
#define STACK_FRAME_CONSTANTS_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * https://docs.google.com/document/d/1xv1blPW4oOIhHJM0B4gJTwqLPzgFY1xZXOZ3HjLlL6E/edit
 *
 */

#include "stack_frame_dep.h"

#define INDEX_CONTENT 0
#define INDEX_SIZE 1
#define INDEX_PAYLOAD 2


#define CRC_SIZE 1
#define LEN_SIZE 1
#define CONTENT_CODE_SIZE 1
#define SF_DOUBLE_SIZE (CONTENT_CODE_SIZE+LEN_SIZE+sizeof(double)+CRC_SIZE)
#define SF_OPERATION_SIZE (CONTENT_CODE_SIZE+LEN_SIZE+1+CRC_SIZE)

typedef enum {
    OPERATION_SUM    =1,
    OPERATION_SUBTRACTION    =2,
    OPERATION_MULTIPLICATION    =3,
    OPERATION_DIVISION =4,
	OPERATION_XOR =5,
	OPERATION_POW =6,
	OPERATION_AND =7,
	OPERATION_OR = 8,

    OPERATION_UNDEF =0,
} Operation_t;


typedef enum {
    STACK_CONTENT_TYPE_ARRAY=1,
    STACK_CONTENT_TYPE_BOOL=2,
    STACK_CONTENT_TYPE_INT8=3,
    STACK_CONTENT_TYPE_UINT8=4,
    STACK_CONTENT_TYPE_INT16=5,
    STACK_CONTENT_TYPE_UINT16=6,
    STACK_CONTENT_TYPE_UINT32=7,
    STACK_CONTENT_TYPE_UINT32_HEX=8,
    STACK_CONTENT_TYPE_INT32=9,
    STACK_CONTENT_TYPE_UINT64=10,
    STACK_CONTENT_TYPE_INT64=11,
    STACK_CONTENT_TYPE_STRING=12,
    STACK_CONTENT_TYPE_FLOAT=13,
    STACK_CONTENT_TYPE_DOUBLE=14,
    STACK_CONTENT_TYPE_STRUCT=15,
    STACK_CONTENT_TYPE_TIME_DATE=16,
    STACK_CONTENT_TYPE_OPERATION=17,

    STACK_CONTENT_TYPE_UNDEF=0,
} StackContentType_t;




#ifdef __cplusplus
}
#endif

#endif /* STACK_FRAME_CONSTANTS_H */
