
$(info I2S_FULL_DUPLEX_GENERAL_PRECONFIG_MK_INC=  $(I2S_FULL_DUPLEX_GENERAL_PRECONFIG_MK_INC) )
ifneq ($(I2S_FULL_DUPLEX_GENERAL_PRECONFIG_MK_INC),Y)
    I2S_FULL_DUPLEX_GENERAL_PRECONFIG_MK_INC=Y

    DMA=Y
    I2S=Y
    I2S_DMA=Y
    MCAL=Y
    TIMER=Y
endif