
$(info I2S_GENERAL_PRECONFIG_MK_INC=  $(I2S_GENERAL_PRECONFIG_MK_INC) )
ifneq ($(I2S_GENERAL_PRECONFIG_MK_INC),Y)
    I2S_GENERAL_PRECONFIG_MK_INC=Y

    I2S_MAL_DIR = $(MCAL_COMMON_DIR)/i2s
    #@echo $(error I2S_MAL_DIR=$(I2S_MAL_DIR))
    I2S=Y
    #COMPLEX=Y
    #DSP=Y
    #DFT=Y
    GPIO=Y
    MICROCONTROLLER=Y
    MULTIMEDIA=Y
    MCAL=Y
    AUDIO=Y

endif