
$(info SCHMITT_TRIGGER_PRECONFIG_INC=$(SCHMITT_TRIGGER_PRECONFIG_INC))

ifneq ($(SCHMITT_TRIGGER_PRECONFIG_INC),Y)
    SCHMITT_TRIGGER_PRECONFIG_INC=Y

    SCHMITT_TRIGGER=Y
    COMPUTING=Y
    DSP=Y
    
endif