$(info QUAD_MIX_4FS_PRECONFIG_INC=$(QUAD_MIX_4FS_PRECONFIG_INC) )

ifneq ($(QUAD_MIX_4FS_PRECONFIG_INC),Y)
    QUAD_MIX_4FS_PRECONFIG_INC=Y

    QUAD_MIX_4FS=Y
    SLIDING_INTEGRAL=Y
    DSP=Y
    #FIR=Y
    #IIR=Y
    #COMPLEX=Y
endif
