$(info ADC_NRF_DRV_PRECONFIG_MK_INCLUDE=$(ADC_NRF_DRV_PRECONFIG_MK_INCLUDE))
ifneq ($(ADC_NRF_DRV_PRECONFIG_MK_INCLUDE),Y)
    ADC_NRF_DRV_PRECONFIG_MK_INCLUDE=Y


    ADC_NRF_DIR = $(MCAL_NRF5340_DIR)/adc
    #@echo $(error ADC_NRF_DIR=$(ADC_NRF_DIR))

    ADC=Y
endif