#ifndef DAC_CHANNEL_CUSTOM_CONST_H
#define DAC_CHANNEL_CUSTOM_CONST_H

#define DAC_CHANNEL_CUSTOM_DRV_VER 1

#define DAC_12BIT_MAX 4095
#define DAC_12BIT_HALF (DAC_12BIT_MAX/2)

#endif /* DAC_CHANNEL_CUSTOM_CONST_H  */
