$(info DEV_E_BOX_STM32FXX_M_V3_0_PRECONFIG_MK_INC=$(DEV_E_BOX_STM32FXX_M_V3_0_PRECONFIG_MK_INC))
ifneq ($(DEV_E_BOX_STM32FXX_M_V3_0_PRECONFIG_MK_INC),Y)
    DEV_E_BOX_STM32FXX_M_V3_0_PRECONFIG_MK_INC=Y

    BOARD_CFG_DIR = $(BOARD_DIR)/dev_e_box_stm32Fxx_m_v3_0

    ASICS=Y
    DEV_E_BOX_STM32FXX_M_V3_0=Y
    STM32=Y
    STM32F407VG=Y
    MICROCONTROLLER=Y

endif
