#ifndef DMA_MCAL_CHANNEL_CONST_H
#define DMA_MCAL_CHANNEL_CONST_H

//#include "time_mcal.h"
#include "dma_channel_dep.h"

#define DMA_CHANNEL_VERSION 4
#define DMA_CHANNEL_PERIOD_US 500000
#define DMA_CHANNEL_TRANSFER_TIMEOUT_MS 3000




typedef enum {
   //DMA_CHANNEL_NUM_UNDEF = 0,

   DMA_CHANNEL_NUM_MEMCPY1 ,
   DMA_CHANNEL_NUM_MEMCPY2 ,

#ifdef HAS_GPIO
   DMA_CHANNEL_NUM_GPIOA_RX,
   DMA_CHANNEL_NUM_GPIOA_TX,
   DMA_CHANNEL_NUM_GPIOB,
   DMA_CHANNEL_NUM_GPIOC,
   DMA_CHANNEL_NUM_GPIOD,
   DMA_CHANNEL_NUM_GPIOE,
#endif

#ifdef HAS_ADC1
   DMA_CHANNEL_NUM_ADC1 ,
#endif

#ifdef HAS_ADC2
   DMA_CHANNEL_NUM_ADC2 ,
#endif

#ifdef HAS_ADC3
   DMA_CHANNEL_NUM_ADC3,
#endif

#ifdef HAS_SDIO
   DMA_CHANNEL_NUM_SDIO_RX ,
   DMA_CHANNEL_NUM_SDIO_TX ,
#endif

#ifdef HAS_SPI1
   DMA_CHANNEL_NUM_SPI1_TX ,
   DMA_CHANNEL_NUM_SPI1_RX ,
#endif

#ifdef HAS_SPI2
   DMA_CHANNEL_NUM_SPI2_TX ,
   DMA_CHANNEL_NUM_SPI2_RX ,
#endif

#ifdef HAS_I2S2
   DMA_CHANNEL_NUM_I2S2_TX ,
   DMA_CHANNEL_NUM_I2S2_RX ,
#endif

#ifdef HAS_SPI3
   DMA_CHANNEL_NUM_SPI3_TX ,
   DMA_CHANNEL_NUM_SPI3_RX ,
#endif


#ifdef HAS_UART_DMA

#ifdef HAS_UART1
   DMA_CHANNEL_NUM_UART1_TX ,
   DMA_CHANNEL_NUM_UART1_RX ,
#endif

#ifdef HAS_UART2
   DMA_CHANNEL_NUM_UART2_TX ,
   DMA_CHANNEL_NUM_UART2_RX ,
#endif

#endif

   DMA_CHANNEL_NUM_CNT
}DmaChannelLegalNums_t;

/* rename to abstract channel type
  DMA_CHANNEL_0, DMA_CHANNEL_1 - busy names in DMA_ChannelType (module_driver_dma.h) */
typedef enum {
    DMA_MCAL_CHANNEL_0  = 0,
    DMA_MCAL_CHANNEL_1  = 1,
    DMA_MCAL_CHANNEL_2  = 2,
    DMA_MCAL_CHANNEL_3  = 3,
    DMA_MCAL_CHANNEL_4  = 4,
    DMA_MCAL_CHANNEL_5  = 5,
    DMA_MCAL_CHANNEL_6  = 6,
    DMA_MCAL_CHANNEL_7  = 7,
    DMA_MCAL_CHANNEL_8  = 8,
    DMA_MCAL_CHANNEL_9  = 9,
    DMA_MCAL_CHANNEL_10 = 10,
    DMA_MCAL_CHANNEL_11 = 11,
    DMA_MCAL_CHANNEL_12 = 12,
    DMA_MCAL_CHANNEL_13 = 13,
    DMA_MCAL_CHANNEL_14 = 14,
    DMA_MCAL_CHANNEL_15 = 15,
    DMA_MCAL_CHANNEL_16 = 16,
    DMA_MCAL_CHANNEL_17 = 17,
    DMA_MCAL_CHANNEL_18 = 18,
    DMA_MCAL_CHANNEL_19 = 19,
    DMA_MCAL_CHANNEL_20 = 20,
    DMA_MCAL_CHANNEL_21 = 21,
    DMA_MCAL_CHANNEL_22 = 22,
    DMA_MCAL_CHANNEL_23 = 23,
    DMA_MCAL_CHANNEL_24 = 24,
    DMA_MCAL_CHANNEL_25 = 25,
    DMA_MCAL_CHANNEL_26 = 26,
    DMA_MCAL_CHANNEL_27 = 27,
    DMA_MCAL_CHANNEL_28 = 28,
    DMA_MCAL_CHANNEL_29 = 29,
    DMA_MCAL_CHANNEL_30 = 30,
    DMA_MCAL_CHANNEL_31 = 31,

    DMA_MCAL_CHANNEL_UNDEF = 0xFF,
} DmaMcalChannel_t;



#endif /* DMA_MCAL_CHANNEL_CONST_H */
