
$(info TEST_I2S_FULL_DUPLEX_MK_INC=$(TEST_I2S_FULL_DUPLEX_MK_INC))

ifneq ($(TEST_I2S_FULL_DUPLEX_MK_INC),Y)
    TEST_I2S_FULL_DUPLEX_MK_INC=Y

    TEST_I2S_FULL_DUPLEX_DIR = $(TEST_SET_HW_DIR)/test_i2s_full_duplex
    #@echo $(error TEST_I2S_FULL_DUPLEX_DIR=$(TEST_I2S_FULL_DUPLEX_DIR))
    INCDIR += -I$(TEST_I2S_FULL_DUPLEX_DIR)
    OPT += -DHAS_TEST_I2S_FULL_DUPLEX

    SOURCES_C += $(TEST_I2S_FULL_DUPLEX_DIR)/test_i2s_full_duplex.c
endif