#ifndef EEPROM_MIK_CONST_H
#define EEPROM_MIK_CONST_H

#include "macro_utils.h"

#define QWORD_LEN 4

#ifndef HAS_MIK32
#error "+HAS_MIK32"
#endif

#ifndef HAS_MICROCONTROLLER
#error "+HAS_MICROCONTROLLER"
#endif

#define EEPROM_OPERATION_TIMEOUT 20000
#define EEPROM_CHUNK_SIZE (16*8)

typedef enum {
    EEPROM_EECON_WRBEH_ORDINARY_ERASE = 0,
    EEPROM_EECON_WRBEH_ERASE_PROGRAM_ALL_EVEN_PAGES = 1,
    EEPROM_EECON_WRBEH_ERASE_PROGRAM_ALL_ODD_PAGES = 2,
    EEPROM_EECON_WRBEH_ERASE_PROGRAM_ALL_PAGES = 3,
    EEPROM_EECON_WRBEH_UNDEF = 4,
} EEPROM_EECON_WRBEH_t;

typedef enum {
    EEPROM_EECON_OPERATION_READ_PAGE = 0,
    EEPROM_EECON_OPERATION_ERASE = 1,
    EEPROM_EECON_OPERATION_PROGRAM = 2,
    EEPROM_EECON_OPERATION_NO_USE = 3,
    EEPROM_EECON_OPERATION_UNDEF = 4,
} EEPROM_EECON_OPERATION_t;

typedef enum {
    EEPROM_EECON_BWE_BUFFER_WRITE_DISABLE = 0,
    EEPROM_EECON_BWE_BUFFER_WRITE_ENABLE = 1,
    EEPROM_EECON_BWE_UNDEF = 2,
} EepromEECON_BWE_t;

typedef enum {
    EEPROM_EESTA_BSY_FREE = 0,
    EEPROM_EESTA_BSY_IN_PROCCESS = 1,
    EEPROM_EESTA_BSY_UNDEF = 2,
} EepromEESTA_BSY_t;

//#define EEPROM_OPERATION_TIMEOUT 40000
#define EEPROM_WR_TIME_MS 20
#define MAX_SINGLE_WRITE_SIZE 256

#endif /* EEPROM_MIK_CONST_H  */
