$(info AUTO_VOLUME_PRECONFIG=$(AUTO_VOLUME_PRECONFIG))

ifneq ($(AUTO_VOLUME_PRECONFIG),Y)
    AUTO_VOLUME_DRV_MK_LOG=Y

    AUTO_VOLUME_DRV_DIR = $(APPLICATIONS_DIR)/auto_volume

    AUTO_VOLUME=Y
    SCHMITT_TRIGGER=Y
    DISTANCE=Y

endif