#ifndef PDM_CUSTOM_CONST_H
#define PDM_CUSTOM_CONST_H

#define PDM_SAMPLE_RATE 16000
#define PDM_CHANNEL_BIT 16
#define PDM_CHANNEL_BYTE (PDM_CHANNEL_BIT / 8)

//#define PDM_CHAN_CNT_DEFAULT 1
//#define PDM_SAMPLES_CNT_0_5_S ((PDM_SAMPLE_RATE * 1) / 2)
//#define PDM_SAMPLES_CNT_0_25_S ((PDM_SAMPLE_RATE * 1) / 4)
//#define PDM_SAMPLES_CNT_0_125_S ((PDM_SAMPLE_RATE * 1) / 8)
//#define PDM_SAMPLES_CNT_62_MS ((PDM_SAMPLE_RATE * 1) / 16)
//#define PDM_SAMPLES_CNT_DEFAULT (PDM_SAMPLES_CNT_62_MS)

#endif /* PDM_CUSTOM_CONST_H  */
