$(info STM32_F4VE_PRECONFIG_MK_INC=$(STM32_F4VE_PRECONFIG_MK_INC))
ifneq ($(STM32_F4VE_PRECONFIG_MK_INC),Y)
    STM32_F4VE_PRECONFIG_MK_INC=Y

    BOARD_CFG_DIR = $(BOARD_DIR)/stm32_f4ve

    ASICS=Y
    STM32_F4VE=Y
    STM32=Y
    STM32F407VG=Y
    MICROCONTROLLER=Y

endif
