#ifndef FLASH_STM32F407VE_CONST_H
#define FLASH_STM32F407VE_CONST_H

#include "macro_utils.h"

#ifndef HAS_FLASH
#error "+HAS_FLASH"
#endif

#define QWORD_LEN 4

#define FLASH_START_APP_CORE   (0x00000000)
#define FLASH_SIZE_APP_CORE (1024 * K_BYTES)
#define NOR_FLASH_APP_PAGE_SIZE (4*K_BYTES)

#define FLASH_START_NET_CORE 0x01000000
#define FLASH_SIZE_NET_CORE (256 * K_BYTES)
#define NOR_FLASH_NET_PAGE_SIZE (2*K_BYTES)

#ifdef HAS_CORE_APP
#define NOR_FLASH_START    FLASH_START_APP_CORE
#define NOR_FLASH_SIZE (1024*K_BYTES)
#define NOR_FLASH_PAGE_SIZE (4*K_BYTES)
#endif

#define FLASH_END_APP_CORE (FLASH_START_APP_CORE+FLASH_SIZE_APP_CORE)
#define FLASH_END_NET_CORE (FLASH_START_NET_CORE+FLASH_SIZE_NET_CORE)

#define NOR_FLASH_PAGE_CNT ((NOR_FLASH_SIZE)/(NOR_FLASH_PAGE_SIZE))

#endif /* FLASH_STM32F407VE_CONST_H  */
