#ifndef CORRELATOR_NAIV_S16_DEP_H
#define CORRELATOR_NAIV_S16_DEP_H

#ifndef HAS_CIRCULAR_BUFFER
#error "+HAS_CIRCULAR_BUFFER"
#endif /*HAS_CIRCULAR_BUFFER*/

#ifndef HAS_COMPUTING
#error "+HAS_COMPUTING"
#endif /*HAS_COMPUTING*/

#ifndef HAS_CORRELATOR_NAIV_S16
#error "+HAS_CORRELATOR_NAIV_S16"
#endif /*HAS_CORRELATOR_NAIV_S16*/

#endif /* CORRELATOR_NAIV_S16_DEP_H */
