

$(info NRF5340_DK_PRECONFIG_MK_INC=$(NRF5340_DK_PRECONFIG_MK_INC))
ifneq ($(NRF5340_DK_PRECONFIG_MK_INC),Y)
    NRF5340_DK_PRECONFIG_MK_INC=Y

    BOARD_CFG_DIR = $(BOARD_DIR)/nrf5340_dk

    ASICS=Y
    NRF5340=Y
    MICROCONTROLLER=Y
    INTERFACES=Y
    NRF5340_DK=Y
    #MX25R6435F=N
    #BUTTON=Y
    #LED=Y
    #UART=Y
    #LED_MONO=Y

endif
