#ifndef MANCHESTER_DECODE_CONST_H
#define MANCHESTER_DECODE_CONST_H

#include "time_mcal.h"
#include "manchester_decode_dep.h"

#define MANCHESTER_DECODE_VERSION 1
#define MANCHESTER_DECODE_PERIOD_US MSEC_2_USEC(500)

typedef enum {
 /*  prev prev  |   prev   |  rx state  */
    MANCH_DECODE_STATE_00_START0=0,
    MANCH_DECODE_STATE_01_START0,
    MANCH_DECODE_STATE_10_START0,
    MANCH_DECODE_STATE_11_START0,
    MANCH_DECODE_STATE_00_START1,
    MANCH_DECODE_STATE_01_START1,
    MANCH_DECODE_STATE_10_START1,
    MANCH_DECODE_STATE_11_START1,
    MANCH_DECODE_STATE_00_DONE,
    MANCH_DECODE_STATE_01_DONE,
    MANCH_DECODE_STATE_10_DONE,
    MANCH_DECODE_STATE_11_DONE,
    MANCH_DECODE_STATE_UNDEF ,
}ManchesterDecodeState_t;

typedef enum{
    MANCH_DECODE_ACTION_ERROR,
    MANCH_DECODE_ACTION_RX0,
    MANCH_DECODE_ACTION_RX1,
    MANCH_DECODE_ACTION_START0,
    MANCH_DECODE_ACTION_START1,
    MANCH_DECODE_ACTION_UNREAL,
    MANCH_DECODE_ACTION_UNDEF,
}ManchesterDecodeAction_t;

#endif /* MANCHESTER_DECODE_CONST_H */
