ifneq ($(HW_CALC_KIT_PRECONFIG_MK_INC),Y)
    HW_CALC_KIT_PRECONFIG_MK_INC=Y
    ANALOG_FILTER=Y
    PLL_CALC=Y
    VOLTAGE_DIVIDER=Y
    SOLVER_SLAE=Y
    SOLVER=Y
    
    ANALOG_FILTER_COMMANDS=Y
    PLL_CALC_COMMANDS=Y
    VOLTAGE_DIVIDER_COMMANDS=Y
    SOLVER_SLAE_COMMANDS=Y
    SOLVER_COMMANDS=Y
endif