$(info TEST_CORRELATOR_S16_MK_INC=$(TEST_CORRELATOR_S16_MK_INC))

ifneq ($(TEST_CORRELATOR_S16_MK_INC),Y)
    TEST_CORRELATOR_S16_MK_INC=Y

    ifneq ($(CORRELATOR_S16),Y)
        @echo $(error +CORRELATOR_S16)
    endif

    TEST_CORRELATOR_S16_DIR = $(TEST_SET_SW_DIR)/test_correlator_s16
    # $(error TEST_CORRELATOR_S16_DIR= $(TEST_CORRELATOR_S16_DIR))

    MCAL_OPT += -DHAS_TEST_SUIT_CORRELATOR_S16
    MCAL_OPT += -DHAS_TEST_CORRELATOR_S16
    INCDIR  += -I$(TEST_CORRELATOR_S16_DIR)

    SOURCES_C += $(TEST_CORRELATOR_S16_DIR)/test_correlator_s16.c
endif
