$(info TEST_SOFTWARE_TIMER_MK_INC=$(TEST_SOFTWARE_TIMER_MK_INC))

ifneq ($(TEST_SOFTWARE_TIMER_MK_INC),Y)
    TEST_SOFTWARE_TIMER_MK_INC=Y


    TEST_SOFTWARE_TIMER_DIR = $(TEST_SET_HW_DIR)/test_sw_timer
    #@echo $(error TEST_SOFTWARE_TIMER_DIR=$(TEST_SOFTWARE_TIMER_DIR))

    INCDIR += -I$(TEST_SOFTWARE_TIMER_DIR)
    OPT += -DHAS_TEST_SOFTWARE_TIMER
    SOURCES_C += $(TEST_SOFTWARE_TIMER_DIR)/test_sw_timer.c
endif