
ifneq ($(CIRCULAR_BUFFER_TEST_CASE_MK_INC),Y)
    CIRCULAR_BUFFER_TEST_CASE_MK_INC=Y

    TEST_CIRCULAR_BUFFER_DIR=$(TEST_SET_SW_DIR)/test_circular_buffer
    #@echo $(error TEST_CIRCULAR_BUFFER_DIR=$(TEST_CIRCULAR_BUFFER_DIR))

    INCDIR += -I$(TEST_CIRCULAR_BUFFER_DIR)
    OPT += -DHAS_TEST_CIRCULAR_BUFFER
    OPT += -DHAS_TEST_SUIT_CIRCULAR_BUFFER

    SOURCES_C +=$(TEST_CIRCULAR_BUFFER_DIR)/test_circular_buffer_indexer.c

endif