
ifneq ($(CLOCKS_GENERAL_PRECONFIG_MK_INC),Y)
    CLOCKS_GENERAL_PRECONFIG_MK_INC=Y

    CLOCK_MCAL_DIR = $(SENSITIVITY_DIR)/clock
    #@echo $(error CLOCK_MCAL_DIR=$(CLOCK_MCAL_DIR))

    CLOCK=Y
    TIME=Y

endif
