#ifndef QUADRATURE_MIXER_DEP_H
#define QUADRATURE_MIXER_DEP_H

#ifndef HAS_CIRCULAR_BUFFER
#error "+HAS_CIRCULAR_BUFFER"
#endif /*HAS_CIRCULAR_BUFFER*/

#ifndef HAS_COMPUTING
#error "+HAS_COMPUTING"
#endif /*HAS_COMPUTING*/

#ifndef HAS_QUADRATURE_MIXER
#error "+HAS_QUADRATURE_MIXER"
#endif /*HAS_QUADRATURE_MIXER*/

#endif /* QUADRATURE_MIXER_DEP_H */
