$(info QUADRATURE_MIXER_PRECONFIG_INC=$(QUADRATURE_MIXER_PRECONFIG_INC) )

ifneq ($(QUADRATURE_MIXER_PRECONFIG_INC),Y)
    QUADRATURE_MIXER_PRECONFIG_INC=Y

    QUADRATURE_MIXER=Y
    #FIR=Y
    #IIR=Y
    COMPLEX=Y
    DSP=Y

endif
