$(info BOARD_CONFIG_CAM_MK_INC=$(BOARD_CONFIG_CAM_MK_INC) )

ifneq ($(BOARD_CONFIG_CAM_MK_INC),Y)
    BOARD_CONFIG_CAM_MK_INC=Y

    BOARD_CONFIG_CAM_DIR = $(BOARD_CUSTOM_DIR)/config_cam
    #@echo $(error BOARD_CONFIG_CAM_DIR=$(BOARD_CONFIG_CAM_DIR))
    INCDIR += -I$(BOARD_CONFIG_CAM_DIR)

    SOURCES_THIRD_PARTY_C += $(BOARD_CONFIG_CAM_DIR)/CAN_packets.c

    MCAL_OPT += -DHAS_BOARD_CONFIG_CAM
endif