$(info CORTEX_M4_PRECONFIG_MK_INC=$(CORTEX_M4_PRECONFIG_MK_INC) )
ifneq ($(CORTEX_M4_PRECONFIG_MK_INC),Y)
    CORTEX_M4_PRECONFIG_MK_INC=Y


    CORTEX_M4_DIR = $(CORE_DIR)/cortex_m4

    ARM=Y
    CORTEX_M4=Y
    CORTEX_M=Y
    MICROCONTROLLER=Y
endif