$(info NUCLEO_F413ZH_PRECONFIG_MK_INC=$(NUCLEO_F413ZH_PRECONFIG_MK_INC))
ifneq ($(NUCLEO_F413ZH_PRECONFIG_MK_INC),Y)
    NUCLEO_F413ZH_PRECONFIG_MK_INC=Y

    BOARD_CFG_DIR = $(BOARD_DIR)/nucleo_f413zh

    MICROCONTROLLER=Y
    NUCLEO_F413ZH=Y
    STM32=Y
    STM32F413ZH=Y
    LED_MONO=Y
endif
